# Rhye's and Fall of Civilization - Constants
# globals

from CvPythonExtensions import *
from DataStructures import *
from CoreTypes import *

gc = CyGlobalContext()

iWorldX = 150
iWorldY = 80

iNumPlayers = gc.getMAX_PLAYERS()

# civilizations, not players
iNumCivs = 114
(iAdal, iAmerica, iArabia, iArgentina, iArmenia, iAshanti, iAssyria, iAustralia, iAztecs, iBabylonia, iBelgium, iBenin, iBoers, iBrazil, iBuganda, iBurma, iBuyids, iByzantium, iCanada, 
iCarthage, iCelts, iChina, iColombia, iDravidia, iEgypt, iElam, iEngland, iEthiopia, iFrance, iFunj, iGeorgia, iGermania, iGermany, iGhana, iGhorids, iGokturks, iGoths,
iGreece, iHarappa, iHausa, iHittites, iHolyRome, iHuns, iInca, iIndia, iIran, iItaly, iJapan, iJava, iJerusalem, iJudah, iKanemBornu, iKatanga, iKhazars,
iKhmer, iCongo, iKorea, iKushans, iMacedon, iMadagascar, iMalays, iMali, iMisr, iManchuria, iMaya, iMexico, iMinoa, iMongols, iMoors, iMorocco, 
iMycenae, iNativeAmericans, iNetherlands, iNorse, iNubia, iNumidia, iOman, iOttomans, iParthia, iPersia, iPoland, iPolynesia, iPortugal, 
iRome, iRus, iRussia, iSamanids, iScythia, iSomalia, iSonghai, iSouthAfrica, iSaudis, iSpain, iSparta, iSumeria, iSwahili, iSweden, iTatars, iThailand, iTibet, iTimurids, iToltecs, iTunis,
iTurks, iVandals, iVietnam, iYemen, iZimbabwe, iZulu, iIndependent, iIndependent2, iNative, iMinor, iBarbarian) = tuple(Civ(i) for i in range(iNumCivs))

iPhoenicia = iCarthage
iMughals = iTimurids

lBirthOrder = [
	iEgypt,
	iSumeria,
	iHarappa,
	iMinoa,
	iElam,
	iNubia,
	iChina,
	iBabylonia,
	iHittites,
	iMycenae,
	iIndia,
	iAssyria,
	iCarthage,
	iJudah,
	iPolynesia,
	iScythia,
	iGreece,
	iSparta,
	iPersia,
	iCelts,
	iMaya,
	iMacedon,
	iNumidia,
	iRome,
	iArmenia,
	iGermania,
	iDravidia,
	iEthiopia,
	iVandals,
	iParthia,
	iToltecs,
	iKushans,
	iKorea,
	iKhmer,
	iGoths,
	iGhana,
	iByzantium,
	iHuns,
	iFrance,
	iMalays,
	iJapan,
	iNorse,
	iGokturks,
	iArabia,
	iTibet,
	iKhazars,
	iKanemBornu,
	iMoors,
	iJava,
	iSpain,
	iGeorgia,
	iEngland,
	iYemen,
	iHolyRome,
	iBurma,
	iHausa,
	iRus,
	iSamanids,
	iBenin,
	iMisr,
	iBuyids,
	iVietnam,
	iSomalia,
	iSwahili,
	iGhorids,
	iBuganda,
	iPoland,
	iTurks,
	iMorocco,
	iJerusalem,
	iPortugal,
	iInca,
	iOman,
	iItaly,
	iMongols,
	iAztecs,
	iZimbabwe,
	iTunis,
	iMali,
	iThailand,
	iSweden,
	iTatars,
	iRussia,
	iAdal,
	iOttomans,
	iTimurids,
	iCongo,
	iSonghai,
	iIran,
	iFunj,
	iMadagascar,
	iNetherlands,
	iKatanga,
	iManchuria,
	iAshanti,
	iGermany,
	iSaudis,
	iAmerica,
	iZulu,
	iBoers,
	iArgentina,
	iMexico,
	iColombia,
	iBrazil,
	iBelgium,
	iAustralia,
	iSouthAfrica,
	iCanada
]

lCivOrder = lBirthOrder + [
	iIndependent,
	iIndependent2,
	iNative,
	iBarbarian
]

# used in: Congresses, DynamicCivs, Plague, RFCUtils, UniquePowers, Victory, Rise
# a civilisation can be in multiple civ groups
iNumCivGroups = 9
(iCivGroupEurope, iCivGroupEastAsia, iCivGroupSouthAsia, iCivGroupMiddleEast, iCivGroupMediterranean, iCivGroupAfrica, iCivGroupAmerica, iCivGroupOceania, iCivGroupNorthAfrica) = range(iNumCivGroups)

dCivGroups = {
iCivGroupEurope : [iVandals, iHuns, iGoths, iMinoa, iMycenae, iGreece, iMacedon, iSparta, iRome, iCelts, iGermania, iByzantium, iGeorgia, iFrance, iNorse, iSpain, iEngland, iHolyRome, iRus, iItaly, iPoland, iPortugal, iSweden, iRussia, iNetherlands, iGermany, iBelgium],
iCivGroupEastAsia : [iChina, iPersia, iJapan, iKorea, iJava, iTibet, iGokturks, iMongols, iRussia, iTurks, iTimurids, iKhazars, iManchuria],
iCivGroupSouthAsia : [iIndia, iHarappa, iPolynesia, iDravidia, iKushans, iKhmer, iMalays, iJava, iBurma, iVietnam, iMughals, iThailand],
iCivGroupMiddleEast : [iEgypt, iSumeria, iElam, iBabylonia, iAssyria, iHittites, iJudah, iScythia, iPersia, iArmenia, iParthia, iKushans, iByzantium, iGeorgia, iArabia, iYemen, iMisr, iSamanids, iBuyids, iSwahili, iOman, iJerusalem, iOttomans, iTurks, iIran, iGhorids, iKhazars, iMorocco, iSaudis, iTatars],
iCivGroupMediterranean : [iMacedon, iEgypt, iGreece, iPhoenicia, iRome, iByzantium, iFrance, iArabia, iMoors, iTunis, iMisr, iSpain, iPortugal, iItaly, iOttomans],
iCivGroupAfrica : [iNubia, iEthiopia, iMali, iGhana, iSwahili, iCongo, iSonghai, iKanemBornu, iBenin, iHausa, iAshanti, iSomalia, iBuganda, iZimbabwe, iAdal, iFunj, iMadagascar, iKatanga, iBoers, iZulu, iSouthAfrica],
iCivGroupAmerica : [iMaya, iToltecs, iInca, iAztecs, iAmerica, iArgentina, iMexico, iColombia, iBrazil, iCanada],
iCivGroupOceania : [iPolynesia, iAustralia],
iCivGroupNorthAfrica : [iEgypt, iCarthage, iVandals, iNumidia, iMoors, iMisr, iTunis, iKanemBornu, iMorocco]

}

# used in: Stability
# tech groups share techs within each other on respawn
iNumTechGroups = 4
(iTechGroupWestern, iTechGroupMiddleEast, iTechGroupFarEast, iTechGroupNativeAmerica) = range(iNumTechGroups)

dTechGroups = {
iTechGroupWestern : [iVandals, iHuns, iGoths, iMinoa, iMycenae, iSparta, iRome, iMacedon, iGreece, iCelts, iGermania, iByzantium, iGeorgia, iFrance, iNorse, iSpain, iEngland, iHolyRome, iRus, iPoland, iPortugal, iItaly, iJerusalem, iSweden, iRussia, iNetherlands, iGermany, iAmerica, iArgentina, iMexico, iColombia, iBrazil, iAustralia, iCanada, iSouthAfrica, iBoers, iBelgium],
iTechGroupMiddleEast : [iEgypt, iSumeria, iElam, iNubia, iBabylonia, iHarappa, iAssyria, iHittites, iJudah, iIndia, iCarthage, iScythia, iPersia, iArmenia, iParthia, iEthiopia, iKushans, iGhana, iMali, iArabia, iYemen, iMoors, iMisr, iSamanids, iBuyids, iSwahili, iOman, iTunis, iOttomans, iDravidia, iCongo, iTurks, iIran, iSonghai, iNumidia, iGhorids, iTimurids, iKanemBornu, iBenin, iHausa, iAshanti, iSomalia, iBuganda, iZimbabwe, iAdal, iFunj, iMadagascar, iKatanga, iZulu, iMorocco, iSaudis, iTatars],
iTechGroupFarEast : [iChina, iKorea, iKhmer, iMalays, iJapan, iJava, iTibet, iBurma, iVietnam, iGokturks, iMongols, iThailand, iKhazars, iManchuria],
iTechGroupNativeAmerica : [iPolynesia, iMaya, iToltecs, iInca, iAztecs],
}

lBioNewWorld = [iMaya, iToltecs, iInca, iAztecs]
lBioOldWorld = [iCiv for iCiv in lBirthOrder if iCiv not in lBioNewWorld]

#for messages
iDuration = 14
iWhite = 0
iRed = 7
iGreen = 8
iBlue = 9
iLightBlue = 10
iYellow = 11
iDarkPink = 12
iLightRed = 20
iPurple = 25
iCyan = 44
iBrown = 55
iOrange = 88
iTan = 90
iLime = 100

# scripted conquerors
iNumConquests = 43

lNeighbours = [
	(iEgypt, iBabylonia),
	(iEgypt, iMinoa),
	(iEgypt, iAssyria),
	(iEgypt, iHittites),
	(iEgypt, iNubia),
	(iEgypt, iMycenae),
	(iEgypt, iGreece),
	(iEgypt, iPersia),
	(iEgypt, iCarthage),
	(iEgypt, iJudah),
	(iEgypt, iSparta),
	(iEgypt, iRome),
	(iEgypt, iEthiopia),
	(iEgypt, iByzantium),
	(iEgypt, iArabia),
	(iEgypt, iSaudis),
	(iEgypt, iMoors),
	(iEgypt, iMorocco),
	(iEgypt, iMacedon),
	(iEgypt, iOttomans),
	(iEgypt, iVandals),
	(iEgypt, iParthia),
	(iEgypt, iMisr),
	(iEgypt, iBuyids),
	(iEgypt, iTunis),
	(iEgypt, iYemen),
	(iEgypt, iOman),
	(iEgypt, iJerusalem),
	(iEgypt, iFunj),
	(iEgypt, iAdal),
	(iBabylonia, iElam),
	(iBabylonia, iAssyria),
	(iBabylonia, iHittites),
	(iBabylonia, iGreece),
	(iBabylonia, iMacedon),
	(iBabylonia, iPersia),
	(iBabylonia, iTurks),
	(iBabylonia, iArabia),
	(iBabylonia, iSaudis),
	(iBabylonia, iOttomans),
	(iBabylonia, iMongols),
	(iBabylonia, iCarthage),
	(iBabylonia, iJudah),
	(iBabylonia, iByzantium),
	(iBabylonia, iIran),
	(iBabylonia, iSumeria),
	(iBabylonia, iScythia),
	(iBabylonia, iArmenia),
	(iBabylonia, iParthia),
	(iBabylonia, iMisr),
	(iBabylonia, iBuyids),
	(iBabylonia, iOman),
	(iBabylonia, iJerusalem),
	(iBabylonia, iGeorgia),
	(iBabylonia, iGhorids),
	(iBabylonia, iTimurids),
	(iSumeria, iAssyria),
	(iSumeria, iElam),
	(iSumeria, iHittites),
	(iSumeria, iGreece),
	(iSumeria, iMacedon),
	(iSumeria, iPersia),
	(iSumeria, iTurks),
	(iSumeria, iArabia),
	(iSumeria, iSaudis),
	(iSumeria, iMongols),
	(iSumeria, iCarthage),
	(iSumeria, iJudah),
	(iSumeria, iIran),
	(iSumeria, iScythia),
	(iSumeria, iArmenia),
	(iSumeria, iMisr),
	(iSumeria, iParthia),
	(iSumeria, iBuyids),
	(iSumeria, iJerusalem),
	(iSumeria, iGeorgia),
	(iSumeria, iGhorids),
	(iSumeria, iTimurids),
	(iHarappa, iElam),
	(iHarappa, iIndia),
	(iHarappa, iPersia),
	(iHarappa, iDravidia),
	(iHarappa, iKushans),
	(iHarappa, iTibet),
	(iHarappa, iIran),
	(iHarappa, iScythia),
	(iHarappa, iParthia),
	(iHarappa, iGhorids),
	(iHarappa, iTimurids),
	(iMinoa, iMycenae),
	(iMinoa, iGreece),
	(iMinoa, iMacedon),
	(iMinoa, iSparta),
	(iMinoa, iHittites),
	(iMinoa, iCarthage),
	(iMinoa, iRome),
	(iMinoa, iByzantium),
	(iMinoa, iArabia),
	(iMinoa, iSaudis),
	(iMinoa, iOttomans),
	(iMinoa, iItaly),
	(iMinoa, iMisr),
	(iMinoa, iTunis),
	(iMinoa, iJerusalem),
	(iElam, iRome),
	(iElam, iKushans),
	(iElam, iTurks),
	(iElam, iByzantium),
	(iElam, iMongols),
	(iElam, iIran),
	(iElam, iMacedon),
	(iElam, iScythia),
	(iElam, iArmenia),
	(iElam, iParthia),
	(iElam, iBuyids),
	(iElam, iSamanids),
	(iElam, iOman),
	(iElam, iGeorgia),
	(iElam, iGhorids),
	(iElam, iTimurids),
	(iAssyria, iHittites),
	(iAssyria, iCarthage),
	(iAssyria, iJudah),
	(iAssyria, iGreece),
	(iAssyria, iMacedon),
	(iAssyria, iPersia),
	(iAssyria, iByzantium),
	(iAssyria, iTurks),
	(iAssyria, iArabia),
	(iAssyria, iSaudis),
	(iAssyria, iOttomans),
	(iAssyria, iIran),
	(iAssyria, iScythia),
	(iAssyria, iArmenia),
	(iAssyria, iParthia),
	(iAssyria, iMisr),
	(iAssyria, iBuyids),
	(iAssyria, iSamanids),
	(iAssyria, iOman),
	(iAssyria, iJerusalem),
	(iAssyria, iGeorgia),
	(iAssyria, iGhorids),
	(iAssyria, iTimurids),
	(iChina, iVietnam),
	(iChina, iKushans),
	(iChina, iJapan),
	(iChina, iKorea),
	(iChina, iGokturks),
	(iChina, iTibet),
	(iChina, iBurma),
	(iChina, iMongols),
	(iChina, iManchuria),
	(iChina, iScythia),
	(iChina, iSamanids),
	(iChina, iGhorids),
	(iChina, iTimurids),
	(iHittites, iMycenae),
	(iHittites, iSparta),
	(iHittites, iGreece),
	(iHittites, iMacedon),
	(iHittites, iCarthage),
	(iHittites, iJudah),
	(iHittites, iPersia),
	(iHittites, iCelts),
	(iHittites, iByzantium),
	(iHittites, iArabia),
	(iHittites, iSaudis),
	(iHittites, iOttomans),
	(iHittites, iIran),
	(iHittites, iHuns),
	(iHittites, iScythia),
	(iHittites, iArmenia),
	(iHittites, iParthia),
	(iHittites, iBuyids),
	(iHittites, iJerusalem),
	(iHittites, iGeorgia),
	(iMycenae, iGreece),
	(iMycenae, iSparta),
	(iMycenae, iJudah),
	(iMycenae, iByzantium),
	(iMycenae, iOttomans),
	(iMycenae, iMacedon),
	(iMycenae, iHuns),
	(iMycenae, iScythia),
	(iMycenae, iGeorgia),
	(iGreece, iCarthage),
	(iGreece, iSparta),
	(iGreece, iJudah),
	(iGreece, iRome),
	(iGreece, iCelts),
	(iGreece, iByzantium),
	(iGreece, iOttomans),
	(iGreece, iItaly),
	(iGreece, iMacedon),
	(iGreece, iGoths),
	(iGreece, iHuns),
	(iGreece, iScythia),
	(iGreece, iJerusalem),
	(iGreece, iGeorgia),
	(iGreece, iTimurids),
	(iGreece, iKhazars),
	(iGreece, iTatars),
	(iSparta, iJudah),
	(iSparta, iRome),
	(iSparta, iItaly),
	(iSparta, iByzantium),
	(iSparta, iOttomans),
	(iSparta, iMacedon),
	(iSparta, iHuns),
	(iSparta, iScythia),
	(iIndia, iPersia),
	(iIndia, iDravidia),
	(iIndia, iKushans),
	(iIndia, iMalays),
	(iIndia, iTibet),
	(iIndia, iJava),
	(iIndia, iKhmer),
	(iIndia, iBurma),
	(iIndia, iIran),
	(iIndia, iScythia),
	(iIndia, iParthia),
	(iIndia, iSamanids),
	(iIndia, iGhorids),
	(iIndia, iTimurids),
	(iCarthage, iJudah),
	(iCarthage, iRome),
	(iCarthage, iSpain),
	(iCarthage, iGhana),
	(iCarthage, iMali),
	(iCarthage, iKanemBornu),
	(iCarthage, iSonghai),
	(iCarthage, iPersia),
	(iCarthage, iArabia),
	(iCarthage, iSaudis),
	(iCarthage, iMoors),
	(iCarthage, iMorocco),
	(iCarthage, iOttomans),
	(iCarthage, iItaly),
	(iPolynesia, iAustralia),
	(iCarthage, iMacedon),
	(iCarthage, iGoths),
	(iCarthage, iVandals),
	(iCarthage, iNumidia),
	(iCarthage, iArmenia),
	(iCarthage, iParthia),
	(iCarthage, iMisr),
	(iCarthage, iBuyids),
	(iCarthage, iJerusalem),
	(iCarthage, iTimurids),
	(iPolynesia, iJava),
	(iPolynesia, iMalays),
	(iJudah, iPersia),
	(iJudah, iByzantium),
	(iJudah, iArabia),
	(iJudah, iSaudis),
	(iJudah, iSaudis),
	(iJudah, iMongols),
	(iJudah, iOttomans),
	(iJudah, iIran),
	(iJudah, iMacedon),
	(iJudah, iParthia),
	(iJudah, iMisr),
	(iJudah, iBuyids),
	(iJudah, iYemen),
	(iJudah, iJerusalem),
	(iJudah, iGeorgia),
	(iJudah, iTimurids),
	(iNubia, iEthiopia),
	(iNubia, iArabia),
	(iNubia, iSaudis),
	(iNubia, iKanemBornu),
	(iNubia, iMacedon),
	(iNubia, iMisr),
	(iNubia, iYemen),
	(iNubia, iOman),
	(iNubia, iAdal),
	(iNubia, iSomalia),
	(iNubia, iFunj),
	(iPersia, iRome),
	(iPersia, iKushans),
	(iPersia, iTurks),
	(iPersia, iGokturks),
	(iPersia, iByzantium),
	(iPersia, iOttomans),
	(iPersia, iMongols),
	(iPersia, iRussia),
	(iPersia, iIran),
	(iPersia, iMacedon),
	(iPersia, iScythia),
	(iPersia, iArmenia),
	(iPersia, iParthia),
	(iPersia, iMisr),
	(iPersia, iBuyids),
	(iPersia, iSamanids),
	(iPersia, iYemen),
	(iPersia, iOman),
	(iPersia, iJerusalem),
	(iPersia, iGeorgia),
	(iPersia, iGhorids),
	(iPersia, iTimurids),
	(iPersia, iKhazars),
	(iPersia, iTatars),
	(iScythia, iTibet),
	(iScythia, iArabia),
	(iScythia, iRus),
	(iScythia, iMongols),
	(iScythia, iOttomans),
	(iScythia, iRome),
	(iScythia, iIran),
	(iScythia, iByzantium),
	(iScythia, iTurks),
	(iScythia, iGokturks),
	(iScythia, iParthia),
	(iScythia, iBuyids),
	(iScythia, iSamanids),
	(iScythia, iGeorgia),
	(iScythia, iGhorids),
	(iScythia, iTimurids),
	(iScythia, iKhazars),
	(iScythia, iTatars),
	(iCelts, iRome),
	(iCelts, iNorse),
	(iCelts, iSpain),
	(iCelts, iFrance),
	(iCelts, iEngland),
	(iCelts, iHolyRome),
	(iCelts, iGermany),
	(iCelts, iGermania),
	(iCelts, iGoths),
	(iCelts, iHuns),
	(iNumidia, iRome),
	(iNumidia, iSpain),
	(iNumidia, iGhana),
	(iNumidia, iMali),
	(iNumidia, iKanemBornu),
	(iNumidia, iSonghai),
	(iNumidia, iArabia),
	(iNumidia, iMoors),
	(iNumidia, iMorocco),
	(iNumidia, iGoths),
	(iNumidia, iVandals),
	(iNumidia, iTunis),
	(iArmenia, iTurks),
	(iArmenia, iByzantium),
	(iArmenia, iOttomans),
	(iArmenia, iMongols),
	(iArmenia, iRussia),
	(iArmenia, iIran),
	(iArmenia, iMacedon),
	(iArmenia, iParthia),
	(iArmenia, iBuyids),
	(iArmenia, iGeorgia),
	(iArmenia, iGhorids),
	(iArmenia, iTimurids),
	(iArmenia, iKhazars),
	(iArmenia, iTatars),
	(iRome, iSpain),
	(iRome, iByzantium),
	(iRome, iFrance),
	(iRome, iHolyRome),
	(iRome, iItaly),
	(iRome, iGermany),
	(iRome, iMoors),
	(iRome, iMorocco),
	(iRome, iMacedon),
	(iRome, iGermania),
	(iRome, iGoths),
	(iRome, iHuns),
	(iRome, iVandals),
	(iRome, iParthia),
	(iRome, iMisr),
	(iRome, iTunis),
	(iRome, iJerusalem),
	(iRome, iGeorgia),
	(iRome, iKhazars),
	(iRome, iTatars),
	(iGermania, iNorse),
	(iGermania, iPoland),
	(iGermania, iFrance),
	(iGermania, iEngland),
	(iGermania, iByzantium),
	(iGermania, iHolyRome),
	(iGermania, iItaly),
	(iGermania, iGoths),
	(iGermania, iHuns),
	(iGermania, iVandals),
	(iMacedon, iByzantium),
	(iMacedon, iOttomans),
	(iMacedon, iItaly),
	(iMacedon, iGoths),
	(iMacedon, iHuns),
	(iMacedon, iParthia),
	(iMacedon, iTunis),
	(iMacedon, iOman),
	(iMacedon, iJerusalem),
	(iMacedon, iGeorgia),
	(iMacedon, iGhorids),
	(iMacedon, iTimurids),
	(iDravidia, iKushans),
	(iDravidia, iMalays),
	(iDravidia, iJava),
	(iDravidia, iKhmer),
	(iDravidia, iBurma),
	(iDravidia, iGhorids),
	(iDravidia, iTimurids),
	(iEthiopia, iArabia),
	(iEthiopia, iSaudis),
	(iEthiopia, iYemen),
	(iEthiopia, iSwahili),
	(iEthiopia, iOman),
	(iEthiopia, iFunj),
	(iEthiopia, iAdal),
	(iEthiopia, iSomalia),
	(iEthiopia, iBuganda),
	(iVandals, iByzantium),
	(iVandals, iArabia),
	(iVandals, iOttomans),
	(iVandals, iHuns),
	(iVandals, iGermany),
	(iVandals, iHolyRome),
	(iVandals, iMoors),
	(iVandals, iMorocco),
	(iVandals, iSpain),
	(iVandals, iPoland),
	(iVandals, iMisr),
	(iVandals, iTunis),
	(iParthia, iKushans),
	(iParthia, iTurks),
	(iParthia, iGokturks),
	(iParthia, iByzantium),
	(iParthia, iOttomans),
	(iParthia, iMongols),
	(iParthia, iRussia),
	(iParthia, iIran),
	(iParthia, iMisr),
	(iParthia, iBuyids),
	(iParthia, iMisr),
	(iParthia, iYemen),
	(iParthia, iOman),
	(iParthia, iJerusalem),
	(iParthia, iGeorgia),
	(iParthia, iGhorids),
	(iParthia, iTimurids),
	(iParthia, iKhazars),
	(iParthia, iTatars),
	(iToltecs, iAztecs),
	(iToltecs, iAmerica),
	(iToltecs, iMexico),
	(iToltecs, iColombia),
	(iKushans, iTurks),
	(iKushans, iGokturks),
	(iKushans, iMongols),
	(iKushans, iIran),
	(iKushans, iOman),
	(iKushans, iGhorids),
	(iKushans, iTimurids),
	(iKushans, iKhazars),
	(iKorea, iMongols),
	(iKorea, iJapan),
	(iKorea, iManchuria),
	(iKhmer, iMalays),
	(iKhmer, iJava),
	(iKhmer, iBurma),
	(iKhmer, iVietnam),
	(iKhmer, iThailand),
	(iGoths, iNorse),
	(iGoths, iPoland),
	(iGoths, iFrance),
	(iGoths, iByzantium),
	(iGoths, iSpain),
	(iGoths, iHolyRome),
	(iGoths, iItaly),
	(iGoths, iHuns),
	(iGoths, iVandals),
	(iGoths, iKhazars),
	(iMali, iMoors),
	(iMali, iMorocco),
	(iMali, iCongo),
	(iMali, iTunis),
	(iMali, iGhana),
	(iMali, iBenin),
	(iMali, iKanemBornu),
	(iMali, iHausa),
	(iMali, iAshanti),
	(iMali, iBuganda),
	(iMali, iFunj),
	(iGhana, iMoors),
	(iGhana, iMorocco),
	(iGhana, iCongo),
	(iGhana, iTunis),
	(iGhana, iSonghai),
	(iGhana, iKanemBornu),
	(iGhana, iBenin),
	(iGhana, iHausa),
	(iGhana, iAshanti),
	(iGhana, iBuganda),
	(iGhana, iFunj),
	(iSonghai, iMoors),
	(iSonghai, iMorocco),
	(iSonghai, iCongo),
	(iSonghai, iTunis),
	(iSonghai, iKanemBornu),
	(iSonghai, iBenin),
	(iSonghai, iHausa),
	(iSonghai, iAshanti),
	(iKanemBornu, iCongo),
	(iKanemBornu, iTunis),
	(iKanemBornu, iSonghai),
	(iKanemBornu, iMoors),
	(iKanemBornu, iMorocco),
	(iKanemBornu, iBenin),
	(iKanemBornu, iAshanti),
	(iKanemBornu, iHausa),
	(iKanemBornu, iFunj),
	(iBenin, iCongo),
	(iBenin, iHausa),
	(iMaya, iToltecs),
	(iMaya, iAztecs),
	(iMaya, iMexico),
	(iMaya, iColombia),
	(iByzantium, iTurks),
	(iByzantium, iArabia),
	(iByzantium, iSaudis),
	(iByzantium, iRus),
	(iByzantium, iMongols),
	(iByzantium, iRussia),
	(iByzantium, iOttomans),
	(iByzantium, iIran),
	(iByzantium, iHuns),
	(iByzantium, iMisr),
	(iByzantium, iBuyids),
	(iByzantium, iTunis),
	(iByzantium, iYemen),
	(iByzantium, iOman),
	(iByzantium, iJerusalem),
	(iByzantium, iGeorgia),
	(iByzantium, iTimurids),
	(iByzantium, iKhazars),
	(iByzantium, iTatars),
	(iHuns, iPoland),
	(iHuns, iRussia),
	(iHuns, iHolyRome),
	(iHuns, iRus),
	(iHuns, iItaly),
	(iHuns, iGermany),
	(iHuns, iFrance),
	(iHuns, iGeorgia),
	(iHuns, iKhazars),
	(iHuns, iTatars),
	(iFrance, iNorse),
	(iFrance, iEngland),
	(iFrance, iHolyRome),
	(iFrance, iNetherlands),
	(iFrance, iItaly),
	(iFrance, iGermany),
	(iFrance, iBelgium),
	(iMalays, iJava),
	(iMalays, iVietnam),
	(iMalays, iThailand),
	(iJapan, iMongols),
	(iJapan, iManchuria),
	(iNorse, iEngland),
	(iNorse, iHolyRome),
	(iNorse, iRus),
	(iNorse, iPoland),
	(iNorse, iSweden),
	(iNorse, iRussia),
	(iNorse, iNetherlands),
	(iNorse, iGermany),
	(iTurks, iArabia),
	(iTurks, iSaudis),
	(iTurks, iRus),
	(iTurks, iMongols),
	(iTurks, iOttomans),
	(iTurks, iIran),
	(iTurks, iMisr),
	(iTurks, iBuyids),
	(iTurks, iSamanids),
	(iTurks, iGokturks),
	(iTurks, iYemen),
	(iTurks, iOman),
	(iTurks, iGeorgia),
	(iTurks, iGhorids),
	(iTurks, iTimurids),
	(iTurks, iKhazars),
	(iTurks, iTatars),
	(iGokturks, iTibet),
	(iGokturks, iArabia),
	(iGokturks, iMongols),
	(iGokturks, iIran),
	(iGokturks, iSamanids),
	(iGokturks, iManchuria),
	(iGokturks, iTatars),
	(iArabia, iMoors),
	(iArabia, iMorocco),
	(iArabia, iSwahili),
	(iArabia, iMongols),
	(iArabia, iOttomans),
	(iArabia, iIran),
	(iArabia, iMisr),
	(iArabia, iBuyids),
	(iArabia, iSamanids),
	(iArabia, iTunis),
	(iArabia, iYemen),
	(iArabia, iOman),
	(iArabia, iJerusalem),
	(iArabia, iGeorgia),
	(iArabia, iGhorids),
	(iArabia, iTimurids),
	(iArabia, iKhazars),
	(iArabia, iFunj),
	(iArabia, iAdal),
	(iArabia, iSomalia),
	(iArabia, iTatars),
	(iTibet, iBurma),
	(iTibet, iMongols),
	(iTibet, iGhorids),
	(iTibet, iTimurids),
	(iTibet, iManchuria),
	(iHausa, iCongo),
	(iKhazars, iGeorgia),
	(iKhazars, iRus),
	(iKhazars, iMongols),
	(iKhazars, iRussia),
	(iKhazars, iIran),
	(iKhazars, iOttomans),
	(iKhazars, iTatars),
	(iMoors, iSpain),
	(iMoors, iPortugal),
	(iMoors, iMisr),
	(iMoors, iTunis),
	(iMorocco, iSpain),
	(iMorocco, iPortugal),
	(iMorocco, iMisr),
	(iMorocco, iTunis),
	(iJava, iThailand),
	(iJava, iAustralia),
	(iSpain, iFrance),
	(iSpain, iPortugal),
	(iSpain, iItaly),
	(iGeorgia, iSamanids),
	(iGeorgia, iMisr),
	(iGeorgia, iBuyids),
	(iGeorgia, iMongols),
	(iGeorgia, iRus),
	(iGeorgia, iRussia),
	(iGeorgia, iOttomans),
	(iGeorgia, iJerusalem),
	(iGeorgia, iIran),
	(iGeorgia, iGhorids),
	(iGeorgia, iTimurids),
	(iGeorgia, iTatars),
	(iEngland, iNetherlands),
	(iYemen, iMisr),
	(iYemen, iOttomans),
	(iYemen, iMongols),
	(iYemen, iOman),
	(iYemen, iFunj),
	(iYemen, iAdal),
	(iYemen, iSomalia),
	(iYemen, iSaudis),
	(iHolyRome, iItaly),
	(iHolyRome, iPoland),
	(iHolyRome, iSweden),
	(iHolyRome, iNetherlands),
	(iHolyRome, iGermany),
	(iHolyRome, iBelgium),
	(iSwahili, iSomalia),
	(iSwahili, iBuganda),
	(iSwahili, iZimbabwe),
	(iSwahili, iBoers),
	(iSwahili, iMadagascar),
	(iSwahili, iSouthAfrica),
	(iSwahili, iZulu),
	(iRus, iPoland),
	(iRus, iMongols),
	(iRus, iSweden),
	(iRus, iRussia),
	(iRus, iOttomans),
	(iRus, iTatars),
	(iMisr, iOttomans),	
	(iMisr, iBuyids),
	(iMisr, iTunis),
	(iMisr, iOman),
	(iMisr, iJerusalem),
	(iMisr, iFunj),
	(iMisr, iAdal),
	(iMisr, iSomalia),
	(iMisr, iSaudis),
	(iMisr, iTatars),
	(iBuyids, iOttomans),
	(iBuyids, iIran),
	(iBuyids, iOman),
	(iBuyids, iJerusalem),
	(iBuyids, iGhorids),
	(iBuyids, iTimurids),
	(iBuyids, iSaudis),
	(iSomalia, iAdal),
	(iSomalia, iFunj),
	(iSomalia, iSaudis),
	(iSomalia, iBuganda),
	(iSamanids, iOttomans),
	(iSamanids, iIran),
	(iSamanids, iGhorids),
	(iSamanids, iTimurids),
	(iSamanids, iManchuria),
	(iSamanids, iSaudis),
	(iVietnam, iBurma),
	(iVietnam, iThailand),
	(iVietnam, iManchuria),
	(iBurma, iThailand),
	(iBurma, iGhorids),
	(iBurma, iTimurids),
	(iBuganda, iZimbabwe),
	(iBuganda, iAdal),
	(iBuganda, iKatanga),
	(iBuganda, iFunj),
	(iBuganda, iKanemBornu),
	(iPoland, iSweden),
	(iPoland, iRussia),
	(iPoland, iGermany),
	(iPoland, iTatars),
	(iJerusalem, iOttomans),
	(iJerusalem, iIran),
	(iJerusalem, iTimurids),
	(iInca, iArgentina),
	(iInca, iColombia),
	(iInca, iBrazil),
	(iOman, iMongols),
	(iOman, iOttomans),
	(iOman, iIran),
	(iOman, iZimbabwe),
	(iOman, iSomalia),
	(iOman, iFunj),
	(iOman, iAdal),
	(iOman, iSaudis),
	(iMongols, iRussia),
	(iMongols, iOttomans),
	(iMongols, iIran),
	(iMongols, iGhorids),
	(iMongols, iTimurids),
	(iMongols, iManchuria),
	(iMongols, iTatars),
	(iAztecs, iAmerica),
	(iAztecs, iMexico),
	(iAztecs, iColombia),
	(iZimbabwe, iKatanga),
	(iZimbabwe, iBoers),
	(iZimbabwe, iSouthAfrica),
	(iZimbabwe, iZulu),
	(iZimbabwe, iMadagascar),
	(iTunis, iOttomans),
	(iTatars, iRussia),
	(iTatars, iOttomans),
	(iTimurids, iIran),
	(iSweden, iRussia),
	(iSweden, iGermany),
	(iRussia, iOttomans),
	(iRussia, iGermany),
	(iRussia, iManchuria),
	(iAdal, iFunj),
	(iAdal, iOttomans),
	(iAdal, iSaudis),
	(iOttomans, iIran),
	(iOttomans, iFunj),
	(iOttomans, iSomalia),	
	(iOttomans, iBuganda),
	(iOttomans, iSaudis),
	(iCongo, iAshanti),
	(iCongo, iKatanga),
	(iMadagascar, iZulu),
	(iMadagascar, iBoers),
	(iMadagascar, iSouthAfrica),
	(iNetherlands, iBelgium),
	(iKatanga, iZulu),
	(iKatanga, iBoers),
	(iKatanga, iSouthAfrica),
	(iAmerica, iMexico),
	(iAmerica, iCanada),
	(iBoers, iZulu),
	(iBoers, iSouthAfrica),
	(iZulu, iSouthAfrica),
	(iArgentina, iBrazil),
	(iMexico, iColombia),
]

lInfluences = [
	(iEgypt, iEngland),
	(iBabylonia, iRome),
	(iBabylonia, iArabia),
	(iIndia, iEngland),
	(iChina, iSomalia),
	(iPhoenicia, iCelts),
	(iPhoenicia, iByzantium),
	(iPhoenicia, iTurks),
	(iPhoenicia, iIran),
	(iPersia, iArabia),
	(iPersia, iSwahili),
	(iRome, iOttomans),
	(iMaya, iSpain),
	(iDravidia, iEngland),
	(iDravidia, iSwahili),
	(iDravidia, iNetherlands),
	(iNumidia, iFrance),
	(iVietnam, iJapan),
	(iVietnam, iFrance),
	(iVietnam, iAmerica),
	(iKhmer, iJapan),
	(iFrance, iTunis),
	(iFrance, iJerusalem),
	(iFrance, iKanemBornu),
	(iFrance, iBenin),
	(iFrance, iHausa),
	(iFrance, iAshanti),
	(iFrance, iBurma),
	(iFrance, iBenin),
	(iFrance, iKanemBornu),
	(iFrance, iHausa),
	(iFrance, iAshanti),
	(iFrance, iBoers),
	(iFrance, iSouthAfrica),
	(iFrance, iZulu),
	(iFrance, iBuganda),
	(iFrance, iMadagascar),
	(iFrance, iZimbabwe),
	(iEngland, iKatanga),
	(iMalays, iJapan),
	(iMalays, iPortugal),
	(iMalays, iNetherlands),
	(iJava, iJapan),
	(iJava, iNetherlands),
	(iArabia, iBabylonia),
	(iArabia, iGreece),
	(iArabia, iPersia),
	(iSpain, iArabia),
	(iSpain, iOttomans),
	(iSpain, iBenin),
	(iSpain, iAshanti),
	(iEngland, iBurma),
	(iEngland, iAustralia),
	(iEngland, iBenin),
	(iEngland, iKanemBornu),
	(iEngland, iHausa),
	(iEngland, iAshanti),
	(iEngland, iBoers),
	(iEngland, iSouthAfrica),
	(iEngland, iZulu),
	(iEngland, iBuganda),
	(iEngland, iMadagascar),
	(iEngland, iZimbabwe),
	(iEngland, iKatanga),	
	(iYemen, iIran),
	(iYemen, iSwahili),
	(iSwahili, iOman),
	(iHolyRome, iOttomans),
	(iBenin, iPortugal),
	(iBenin, iNetherlands),
	(iInca, iSpain),
	(iItaly, iOttomans),
	(iPortugal, iAshanti),
	(iPortugal, iKatanga),
	(iAztecs, iSpain),
	(iTimurids, iEngland),
	(iOttomans, iRome),
	(iThailand, iJapan),
	(iCongo, iPortugal),
	(iCongo, iBelgium),
	(iNetherlands, iSpain),
	(iNetherlands, iAshanti),
	(iNetherlands, iBoers),
	(iNetherlands, iZulu),
	(iNetherlands, iSouthAfrica),
	(iNetherlands, iKatanga),
	(iNetherlands, iAustralia),
	(iAmerica, iEngland),
	(iAmerica, iFrance),
	(iAmerica, iNetherlands),
	(iArgentina, iSpain),
	(iMexico, iSpain),
	(iMexico, iFrance),
	(iColombia, iSpain),
	(iBrazil, iPortugal),
	(iBrazil, iCongo),
	(iCanada, iFrance),
	(iCanada, iEngland),
	(iAmerica, iSaudis),
]

dBirth = CivDict({
iEgypt : -3000,
iSumeria : -3000,
iHarappa : -3000,
iMinoa : -2900,
iElam : -2700,
iNubia : -2200,
iChina : -2070,
iBabylonia : -2000,
iHittites : -1800,
iMycenae : -1750,
iIndia : -1500,
iAssyria : -1400,
iPhoenicia : -1200,
iJudah : -1100,
iPolynesia : -1000,
iScythia : -850,
iGreece : -800,
iSparta : -800,
iPersia : -650,
iCelts : -600,
iMaya : -400,
iMacedon : -400,
iNumidia : -400,
iRome : -338,
iArmenia : -330,
iGermania : -300,
iDravidia : -300,
iEthiopia : -290,
iVandals : -250,
iParthia : -247,
iToltecs : -200,
iKushans : -135,
iKorea : -50,
iKhmer : 50,
iGoths : 150,
iGhana : 300,
iByzantium : 330,
iHuns : 370,
iFrance : 496,
iMalays : 500,
iJapan : 525,
iNorse : 551,
iGokturks : 552,
iArabia : 620,
iTibet : 630,
iKhazars: 640,
iKanemBornu: 700,
iMoors : 711,
iJava : 716,
iSpain : 722,
iGeorgia : 780,
iEngland : 820,
iYemen : 820,
iHolyRome : 840,
iBurma : 849,
iHausa : 850,
iRus : 880,
iSamanids : 892,
iBenin : 900,
iMisr : 909,
iGhorids: 977,
iBuyids : 937,
iVietnam : 938,
iSomalia : 950,
iSwahili : 957,
iBuganda : 1000,
iPoland : 1025,
iTurks : 1037,
iMorocco : 1070,
iJerusalem : 1099,
iPortugal : 1130,
iInca : 1150,
iOman : 1154,
iItaly : 1167,
iMongols : 1190,
iAztecs : 1195,
iZimbabwe : 1220,
iTunis : 1229,
iMali : 1230,
iThailand : 1238,
iSweden : 1252,
iTatars : 1259,
iRussia : 1263,
iAdal : 1275,
iOttomans : 1280,
iTimurids: 1370,
iCongo : 1390,
iSonghai : 1430,
iIran : 1501,
iFunj : 1501,
iMadagascar : 1540,
iNetherlands : 1580,
iKatanga : 1585,
iManchuria : 1586,
iAshanti : 1700,
iGermany : 1700,
iSaudis : 1744,
iAmerica : 1776,
iZulu : 1780,
iBoers : 1795,
iArgentina : 1810,
iMexico : 1810,
iColombia : 1814,
iBrazil : 1822,
iBelgium : 1830,
iAustralia : 1851,
iSouthAfrica : 1853,
iCanada : 1867,
}, -3000)

lBirthCivs = dBirth.keys()

dFall = CivDict({
iEgypt : -343,
iSumeria : -1800,
iHarappa : -1700,
iMinoa : -1200,
iElam : -1000, #Slightly early to allow Persia to start with Elam.
iAssyria : -609,
iNubia : 1365,
iChina : 1127,
iBabylonia : -539,
iHittites : -900,
iMycenae : -1200,
iJudah : -750,
iIndia : 600,
iPhoenicia : 400, # Aeons - Dynamic Mediterranean
iPolynesia : 1200,
iScythia : -200,
iPersia : -330,
iGreece : 400,	# Aeons - Dynamic Mediterranean
iSparta : 400,	# Aeons - Dynamic Mediterranean
iCelts : 1169,
iRome : 400,
iArmenia : 1045,
iGermania : 772,
iMaya : 900,
iMacedon : -260, # A little before Parthia's spawn - modified to allow Parthia to survive.
iNumidia : -25,
iDravidia : 1000,
iEthiopia : 960,
iVandals : 534,
iParthia : 653,
iToltecs : 950,
iKushans : 375,
iMalays : 1511,
iKorea : 1255,
iKhmer : 1200,
iGoths : 600,
iGhana : 1280,
iMali : 1600,
iSonghai : 1591,
iByzantium : 1204,
iHuns : 460,
iNorse : 1300,
iGokturks : 750,
iTurks : 1920,
iArabia : 950,
iTibet : 1500,
iKhazars: 970,
iKanemBornu : 1893,
iMoors : 1500,
iJava: 1755,
iGeorgia: 1463,
iBurma : 1885,
iYemen : 1849,
iHausa : 1903,
iRus : 1300,
iSamanids: 1000,
iBenin : 1897,
iMisr : 1517,
iBuyids : 1062,
iSwahili : 1513,
iSomalia : 1660,
iBuganda : 1890,
iPoland : 1650,
iJerusalem : 1291,
iInca : 1533,
iMongols : 1340, # Slightly early to ensure Timurid birth.
iAztecs : 1600, # Late to allow for colonisers and Mexican colony.
iZimbabwe : 1880,
iTunis : 1574,
iTatars : 1502,
iAdal : 1577,
iGhorids : 1398,
iTimurids : 1640,
iCongo : 1800,
iFunj : 1821,
iMadagascar : 1897,
iKatanga : 1900,
iManchuria : 1860,
iAshanti : 1902,
iBoers : 1902,
iZulu : 1897,
}, 2026)

# Leoreth: determine neighbour lists from pairwise neighbours for easier lookup
dNeighbours = dictFromEdges(lBirthCivs, lNeighbours)

# Leoreth: determine influence lists from pairwise influences for easier lookup
dInfluences = dictFromEdges(lBirthCivs, lInfluences)

dResurrections = CivDict({
iEgypt : [(-3000, -50)],
iBabylonia : [(-2000, -500)],
iAssyria : [(-1400, -600)],
iChina : [(600, 1500), (1800, 2026)],
iHittites : [(-1800, -800)], 	
iNubia : [(500, 1200), (2000, 2026)],
iGreece : [(800, 1000), (1800, 2026)],	#Greece is mutually exclusive with Byz, exists to fill out area if Byz never existed.
iIndia : [(1600, 1800), (1900, 2026)],
iPhoenicia : [(-1000, -150)], 
iCelts : [(400, 1150), (1850, 2026)],
iRome : [(-338, 450)],
iArmenia : [(750, 950), (1920, 2026)],
iMaya : [(0, 800)],
iNumidia : [(1180, 1500), (1950, 2026)],
iDravidia : [(-300, 600), (1300, 1650)],
iEthiopia : [(1270, 1520), (1750, 1880), (1940, 2026)],
iParthia : [(-100, 580)],
iKorea : [(600, 2026)],
iKhmer : [(1950, 2026)],
iMali : [(1340, 1500)],
iByzantium : [(1100, 1280)],
iFrance : [(1500, 2026)],
iMalays : [(500, 1500), (1940, 2026)],
iJapan : [(1800, 2026)],
iNorse : [(1520, 2026)],
iTurks : [(1505, 1700)],
iGokturks : [(600, 700)],
iArabia : [(1100, 1200)],
#iKhazars : [(1200, 1450)], No more Golden Horde period Khazars - We have actual Tatars now
iKanemBornu : [(1100, 1650), (1950, 2026)],
iMoors : [(1220, 1400)],
iJava : [(720, 1755), (1900, 2026)],
iGeorgia : [(1250, 1400), (1990, 2026)],
iSpain : [(1350, 2026)],
iGoths : [(1350, 2026)], # Doesn't occur if Spain or Italy exists (99% of games)
iEngland : [(1700, 2026)],
iYemen : [(1900, 2026)],
iHolyRome : [(1800, 2026)],
iGermania : [(1100, 1650)], # Doesn't occur if HRE exists (99% of games)
iBurma : [(850, 1885), (1950, 2026)],
iHausa : [(1200, 1600), (1950, 2026)],
iRus : [(1970, 2026)],
iBenin : [(1400, 1550), (1950, 2026)],
iMisr : [(1800, 2026)],
iVietnam : [(950, 2026)],
iSwahili : [(1960, 2026)],
iSomalia : [(1200, 1550), (1960, 2026)],
iBuganda : [(1700,1800),(1960, 2026)],
iPoland : [(1920, 2026)],
iMorocco : [(1500, 1800), (1955, 2026)],
iPortugal : [(1700, 2026)],
iInca : [(1800, 1930)],
iOman : [(1600, 2026)],
iItaly : [(1820, 2026)],
iMongols : [(1420, 1560), (1910, 2026)],
iZimbabwe : [(1500,1750),(1950, 2026)],
iTunis : [(1920, 2026)],
iTimurids : [(1526, 1630), (1940, 2026)],
iThailand : [(1700, 2026)],
iSweden : [(1250, 2026)],
iRussia : [(1280, 1550), (1700, 2026)],
iOttomans : [(1505, 2026)],
iFunj : [(1600, 1650), (1960, 2026)],
iIran : [(1505, 2026)],
iMadagascar : [(1700, 1800), (1960, 2026)],
iNetherlands : [(1700, 2026)],
iAshanti : [(1900, 2026)],
iGermany : [(1840, 2026)],
iSaudis : [(1820, 2025)],
iAmerica : [(1776, 2026)],
iArgentina : [(1820, 2026)],
iMexico : [(1820, 2026)],
iColombia : [(1820, 2026)],
iBrazil : [(1820, 2026)],
iBelgium : [(1830, 2026)],
iAustralia : [(1851, 2026)],
iCanada : [(1867, 2026)],
iSouthAfrica : [(1960, 2026)],
}, [])

# Resurrections that occur every 3 turns instead of 10, multiple occur on every turn, and stability requirement is lessened.
dInstantResurrections = CivDict({
iPersia : [(850, 900)],
iJerusalem : [(1100, 1300)],
iNumidia : [(1200, 1250)],
iChina : [(1368, 1400)],
iArabia : [(1400, 1450)],
iTurks : [(1490, 1540)],
iTimurids : [(1526, 1540)],
#iMongols : [(1500, 1530)], Aeons - Removed, doesn't seem that necessary
#iAmerica : [(1776, 1820)],
#iArgentina : [(1820, 1850)],
#iMexico : [(1820, 1850)],
#iColombia : [(1820, 1850)],
#iInca : [(1820, 1850)],
#iBrazil : [(1820, 1850)],
#iCanada : [(1867, 1885)],
iSwahili : [(1960, 1980)],
iSomalia : [(1960, 1980)],
iBuganda : [(1960, 1980)],
iMali : [(1960, 1980)],
iFunj : [(1960, 1980)],
iHausa : [(1960, 1980)],
iZimbabwe : [(1950, 1980)],
iCongo : [(1960, 1980)],
iMadagascar : [(1960, 1980)],
iNubia : [(2005, 2015)],
}, [])

dAggressionLevel = CivDict({
iMorocco: 2,
iZulu : 3,
iBoers : 1,
iZimbabwe : 1,
iSouthAfrica : 2,
iSomalia : 1,
iAdal : 2,
iFunj : 2,
iMadagascar : 1,
iAshanti : 1,
iHausa : 2,
iKanemBornu : 1,
iSonghai : 3,
iMali : 2,
iGeorgia : 2,
iJerusalem : 2,
iOman : 2,
iYemen : 1,
iTunis : 2,
iParthia : 3,
iArmenia : 1,
iScythia : 2,
iNumidia : 2,
iVandals : 2,
iHuns : 3,
iMacedon : 3,
iSumeria : 1,
iMinoa : 1,
iElam : 2,
iAssyria : 3,
iChina : 1,
iBabylonia : 3,
iHittites : 3,
iNubia : 2,
iMycenae : 2,
iGreece : 2,
iJudah : 2,
iPersia : 3,
iSparta : 2,
iCelts : 2,
iRome : 3,
iGermania : 2,
iMaya : 1,
iDravidia : 1,
iToltecs: 1,
iKushans : 1,
iKhmer : 2,
iGoths : 3,
iByzantium : 2,
iFrance : 3,
iJapan : 1,
iNorse : 2,
iTurks : 5,
iGokturks : 3,
iArabia : 2,
iTibet : 1,
iKhazars: 2,
iMoors : 1,
iJava : 1,
iSpain : 2,
iEngland : 3,
iHolyRome : 1,
iRus : 2,
iSamanids: 3,
iBenin : 1,
iMisr : 2,
iBuyids : 2,
iBurma : 2,
iVietnam : 1,
iPoland : 1,
iInca : 1,
iPortugal : 2,
iMongols : 3,
iAztecs : 2,
iTimurids : 3,
iGhorids : 4,
iSweden : 1,
iTatars : 2,
iRussia : 1,
iOttomans : 2,
iIran : 1,
iManchuria : 1,
iGermany : 2,
iAmerica : 2,
iColombia : 2,
iMexico : 1,
iArgentina : 1,
}, 0)

dWarOnFlipProbability = CivDict({
iMorocco: 50,
iZulu : 30,
iBoers : 40,
iZimbabwe : 10,
iSouthAfrica : 20,
iBuganda : 40,
iKatanga : 10,
iSomalia : 60,
iAdal : 80,
iFunj : 90,
iMadagascar : 20,
iAshanti : 30,
iHausa : 40,
iBenin : 10,
iKanemBornu : 15,
iSonghai : 50,
iGhana : 40,
iYemen: 30,
iTunis: 40,
iEgypt: 20,
iSumeria: 30,
iHarappa: 50,
iMinoa: 20,
iElam: 30,
iAssyria: 50,
iChina: 40,
iBabylonia: 50,
iHittites: 50,
iJudah: 75,
iNubia: 20,
iMycenae: 70,
iGreece: 50,
iIndia: 20,
iPhoenicia: 20,
iPolynesia: 20,
iScythia : 20,
iPersia: 30,
iSparta: 40,
iCelts: 20,
iRome: 20,
iArmenia: 20,
iGermania: 15,
iMaya: 20,
iMacedon: 60,
iNumidia: 20,
iDravidia: 20,
iEthiopia: 20,
iVandals: 25,
iParthia: 30,
iToltecs: 20,
iKushans: 30,
iMalays: 30,
iKorea: 20,
iKhmer: 20,
iGoths: 15,
iMali: 30,
iByzantium: 20,
iHuns: 20,
iFrance: 20,
iJapan: 20,
iNorse: 20,
iTurks: 50,
iGokturks: 30,
iArabia: 20,
iTibet: 20,
iJava: 20,
iKhazars: 20,
iMoors: 20,
iSpain: 20,
iGeorgia: 60,
iEngland: 50,
iHolyRome: 20,
iBurma: 40,
iRus: 20,
iMisr: 60,
iBuyids: 20,
iSamanids: 40,
iVietnam: 20,
iSwahili: 20,
iPoland: 60,
iJerusalem : 70,
iPortugal: 60,
iInca: 30,
iOman: 20,
iItaly: 40,
iMongols: 30,
iAztecs: 50,
iGhorids: 50,
iTimurids: 60,
iThailand: 20,
iTatars: 30,
iSweden : 30,
iRussia: 50,
iOttomans: 30,
iCongo: 20,
iIran: 20,
iNetherlands: 60,
iManchuria: 30,
iGermany: 20,
iSaudis: 20,
iAmerica: 50,
iArgentina: 40,
iMexico: 40,
iColombia: 40,
iBrazil: 40,
iBelgium: 60,
iAustralia: 40,
iCanada: 40,
}, 0)

dResurrectionProbability = CivDict({
iMoors: 60,
iMorocco: 60,
iZulu : 0,
iBoers : 0,
iZimbabwe : 20,
iSouthAfrica : 100,
iBuganda : 40,
iKatanga : 0,
iSomalia : 60,
iAdal : 0,
iFunj : 30,
iMadagascar : 40,
iAshanti : 50,
iHausa : 80,
iBenin : 30,
iKanemBornu : 50,
iSonghai : 0,
iGhana : 0,
iEgypt : 25,
iSumeria : 0,
iHarappa : 0,
iMinoa : 0,
iElam : 0,
iAssyria : 40,
iChina : 100,
iBabylonia : 40,
iHittites : 0,
iNubia : 20,
iMycenae : 0,
iGreece : 60,
iIndia : 50,
iPhoenicia : 30,
iJudah : 0,
iPolynesia : 40,
iScythia : 0,
iPersia : 100,
iSparta : 0,
iCelts : 50,
iRome : 65,
iArmenia : 80,
iGermania: 0,
iMaya : 30,
iMacedon : 0,
iNumidia : 100,
iDravidia : 10,
iEthiopia : 80,
iParthia: 60,
iMalays : 60,
iKorea : 80,
iKhmer : 60,
iGoths : 0,
iVandals : 0,
iMali : 30,
iByzantium : 65,
iHuns : 0,
iFrance : 100,
iJapan : 100,
iNorse : 60,
iTurks : 60,
iGokturks : 30,
iArabia : 100,
iTibet : 60,
iKhazars: 50,
iMoors : 70,
iJava : 80,
iSpain : 100,
iGeorgia: 50,
iEngland : 100,
iYemen : 100,
iHolyRome : 80,
iBurma : 60,
iVietnam : 60,
iRus: 60,
iMisr : 80,
iBuyids : 0,
iSamanids: 0,
iSwahili: 40,
iPoland : 65,
iJerusalem : 0,
iPortugal : 100,
iInca : 70,
iOman : 60,
iItaly : 100,
iMongols : 80,
iAztecs : 70,
iTunis : 70,
iTimurids : 100,
iGhorids: 65,
iThailand : 100,
iSweden : 100,
iRussia : 100,
iOttomans : 100,
iCongo : 20,
iIran : 100,
iNetherlands : 100,
iManchuria : 80,
iGermany : 100,
iSaudis : 70,
iAmerica : 100,
iArgentina : 100,
iMexico : 100,
iColombia : 80,
iBrazil : 100,
iBelgium : 100,
iAustralia : 100,
iCanada : 100,
})

dPatienceThreshold = CivDict({
iMorocco: 35,
iZulu : 20,
iBoers : 30,
iZimbabwe : 40,
iSouthAfrica : 30,
iBuganda : 50,
iKatanga : 30,
iSomalia : 30,
iAdal : 20,
iFunj : 25,
iMadagascar : 40,
iAshanti : 35,
iHausa : 30,
iBenin : 50,
iKanemBornu : 40,
iSonghai : 30,
iGhana : 40,
iMinoa : 30,
iEgypt : 30,
iSumeria : 20,
iHarappa : 30,
iElam : 30,
iAssyria : 25,
iChina : 30,
iBabylonia : 30,
iHittites : 30,
iNubia : 30,
iMycenae : 15,
iGreece : 35,
iIndia : 50,
iJudah : 50,
iPhoenicia : 35,
iPolynesia : 50,
iScythia : 30,
iPersia : 30,
iSparta : 25,
iCelts : 25,
iRome : 25,
iArmenia : 40,
iMaya : 35,
iMacedon : 15,
iNumidia : 20,
iDravidia : 45,
iEthiopia : 20,
iVandals : 20,
iParthia: 25,
iToltecs : 20,
iKushans : 25,
iMalays : 40,
iKorea : 25,
iKhmer : 30,
iGoths : 20,
iMali : 35,
iByzantium : 25,
iHuns : 20,
iFrance : 20,
iJapan : 25,
iNorse : 30,
iTurks : 20,
iGokturks : 35,
iArabia : 30,
iTibet : 50,
iKhazars: 20,
iMoors : 20,
iJava : 30,
iSpain : 20,
iGeorgia : 30,
iEngland : 20,
iYemen : 35,
iHolyRome : 20,
iBurma : 30,
iRus : 20,
iMisr : 30,
iBuyids : 20,
iSamanids: 20,
iVietnam : 20,
iSwahili : 40,
iPoland : 20,
iJerusalem : 20,
iPortugal : 30,
iInca : 35,
iOman : 25,
iItaly : 25,
iMongols : 20,
iAztecs : 30,
iTunis : 40,
iTimurids : 35,
iGhorids : 20,
iThailand : 30,
iSweden : 30,
iTatars: 20,
iRussia : 30,
iOttomans : 35,
iCongo : 20,
iIran : 30,
iNetherlands : 30,
iManchuria : 40,
iGermany : 20,
iSaudis : 30,
iAmerica : 30,
iArgentina : 40,
iMexico : 40,
iColombia : 30,
iBrazil : 40,
iBelgium: 30,
iAustralia : 40,
iCanada : 40,
}, 100)


#dMaxColonists = CivDict({
#iSweden : 1,
#iSpain : 8,
#iFrance : 7,
#iEngland : 10,
#iPortugal : 7, 
#iNetherlands : 6,
#iGermany : 2
#})

# Aeons - Raise Colonist numbers
dMaxColonists = CivDict({
iSweden : 2,
iSpain : 10,
iFrance : 7,
iEngland : 12,
iPortugal : 8, 
iNetherlands : 6,
iGermany : 3
})

# initialise religion variables to religion indices from XML
iNumReligions = 11
(iJudaism, iOrthodoxy, iCatholicism, iProtestantism, iIslam, iHinduism, iBuddhism, iConfucianism, iTaoism, iZoroastrianism, iShia) = range(iNumReligions)

#Persecution preference
tPersecutionPreference = (
(iHinduism, iBuddhism, iTaoism, iConfucianism, iZoroastrianism, iShia, iIslam, iProtestantism, iCatholicism, iOrthodoxy), # Judaism
(iShia, iIslam, iProtestantism, iCatholicism, iJudaism, iZoroastrianism, iHinduism, iBuddhism, iTaoism, iConfucianism), # Orthodoxy
(iIslam, iShia, iProtestantism, iOrthodoxy, iJudaism, iZoroastrianism, iHinduism, iBuddhism, iTaoism, iConfucianism), # Catholicism
(iIslam, iShia, iCatholicism, iOrthodoxy, iJudaism, iZoroastrianism, iHinduism, iBuddhism, iTaoism, iConfucianism), # Protestantism
(iHinduism, iShia, iProtestantism, iCatholicism, iOrthodoxy, iJudaism, iTaoism, iConfucianism, iZoroastrianism, iBuddhism), # Islam
(iShia, iIslam, iCatholicism, iProtestantism, iOrthodoxy, iJudaism, iZoroastrianism, iTaoism, iConfucianism, iBuddhism), # Hinduism
(iCatholicism, iProtestantism, iOrthodoxy, iJudaism, iZoroastrianism, iTaoism, iShia, iIslam, iConfucianism, iHinduism), # Buddhism
(iIslam, iShia, iCatholicism, iProtestantism, iOrthodoxy, iJudaism, iZoroastrianism, iHinduism, iBuddhism, iTaoism), # Confucianism
(iIslam, iShia, iCatholicism, iProtestantism, iOrthodoxy, iJudaism, iZoroastrianism, iHinduism, iBuddhism, iConfucianism), # Taoism
(iShia, iIslam, iCatholicism, iProtestantism, iOrthodoxy, iJudaism, iBuddhism, iHinduism, iTaoism, iConfucianism), # Zoroastrianism
(iIslam, iHinduism, iProtestantism, iCatholicism, iOrthodoxy, iJudaism, iTaoism, iConfucianism, iZoroastrianism, iBuddhism), # Shia
)

# pagan religions
iNumPaganReligions = 24
(iAnunnaki, iAsatru, iAtua, iBaalism, iBidaism, iBon, iBukongo, iDruidism, iInti, iMazdaism, iMugyo, iOlympianism, 
iPesedjet, iRodnovery, iShendao, iShinto, iTengri, iTeotlMaya, iTeotlToltec, iTeotlAztec, iVedism, iYoruba, iFombaGasy, iBantu) = range(iNumPaganReligions)

iPaganVictory = iNumReligions
iSecularVictory = iNumReligions + 1

# corporations
iNumCorporations = 12
(iSilkRoute, iTradingCompany, iCerealIndustry, iFishingIndustry, iTextileIndustry, iSteelIndustry, iOilIndustry, iLuxuryIndustry, iAutomobileIndustry, iComputerIndustry, iHanseaticLeague, iKnightsTemplar) = range(iNumCorporations)

# initialise tech variables to unit indices from XML

iNumTechs = 148
(iTanning, iMining, iPottery, iPastoralism, iAgriculture, iMythology, iSailing,
iSmelting, iMasonry, iLeverage, iProperty, iCeremony, iDivination, iSeafaring,
iAlloys, iConstruction, iRiding, iArithmetics, iWriting, iCalendar, iShipbuilding,
iBloomery, iCement, iMathematics, iContract, iLiterature, iPriesthood, iNavigation,
iGeneralship, iEngineering, iAesthetics, iCurrency, iLaw, iPhilosophy, iMedicine,
iRecurveBow, iSteel, iArchitecture, iArtisanry, iPolitics, iScholarship, iEthics,
iNobility, iSpringSteel, iFortification, iLateenSails, iFeudalism, iCivilService, iTheology,
iSelectiveBreeding, iLimbProtection, iMachinery, iAlchemy, iGuilds, iCropRotation, iDoctrine,
iCommune, iDiscipline, iPaper, iCompass, iPatronage, iEducation, iReligiousOrders,
iGunpowder, iCompanies, iFinance, iCartography, iHumanities, iPrinting, iJudiciary,
iFirearms, iLogistics, iExploration, iOptics, iAcademia, iStatecraft, iHeritage,
iCombinedArms, iEconomics, iGeography, iScientificMethod, iUrbanPlanning, iCivilLiberties, iHorticulture,
iReplaceableParts, iHydraulics, iPhysics, iGeology, iMeasurement, iSociology, iSocialContract,
iMachineTools, iThermodynamics, iMetallurgy, iChemistry, iBiology, iRepresentation, iNationalism,
iBallistics, iEngine, iRailroad, iElectricity, iRefrigeration, iCollectivism, iJournalism,
iPneumatics, iAssemblyLine, iRefining, iFilm, iMicrobiology, iConsumerism, iCivilRights,
iInfrastructure, iFlight, iSynthetics, iRadio, iPsychology, iMacroeconomics, iSocialServices,
iAviation, iRocketry, iFission, iElectronics, iTelevision, iPowerProjection, iGlobalism,
iRadar, iSpaceflight, iNuclearPower, iLaser, iComputers, iTourism, iEcology,
iAerodynamics, iSatellites, iSuperconductors, iRobotics, iTelecommunications, iRenewableEnergy, iGenetics,
iSupermaterials, iFusion, iNanotechnology, iCybernetics, iBiotechnology,
iUnifiedTheory, iArtificialIntelligence,
iTranshumanism) = range(iNumTechs)

# initialise unit variables to unit indices from XML

iNumUnits = 300
(iLion, iBear, iPanther, iWolf, iSettler, iAfricanSettler, iCityBuilder, iPioneer, iWorker, iBarbarianWorker, iPunjabiWorker, iLabourer, 
iMadeireiro, iScout, iCaravan, iExplorer, iBandeirante, iSpy, iReligiousPersecutor, iJewishMissionary, iOrthodoxMissionary, iCatholicMissionary, iProtestantMissionary, 
iIslamicMissionary, iHinduMissionary, iBuddhistMissionary, iConfucianMissionary, iTaoistMissionary, iZoroastrianMissionary, iShiaMissionary, iWarrior, iNativeWarrior, iMilitia, iHornedWarrior, iAxeman, iIronAxeman,
iLightSwordsman, iVulture, iDogSoldier, iOathsworn, iSwordsman, iRozwiWarrior, iIyobaWarrior, iJaguar, iMaccabee, iLegion, iGallicWarrior, iGermanicWarrior, iPendekar, iAucac, 
iShotelai, iMaceman, iAbambowa, iWarriorMonk, iHeavySwordsman, iGallowglass, iBarbaryPirate, iSamurai, iHuscarl, iGhazi, iDruzhina, iPombos, iMujahid, iFidai, iLevyman, iSpearman, iAssegaiWielder, iAzmaru, iHoplite, iSpartiate, 
iSacredBand, iImmortal, iNativeRaider, iImpi, iHeavySpearman, iShukuri, iMujahideenSpearman, iDaylamite, iKyundaw, iPikeman, iFoloalindahy, iLandsknecht, iArquebusier, iTwafo, iIronhelm, iHandCannon, iFirelancer, iTercio, 
iStrelets, iJanissary, iOromoWarrior, iQizilbash, iMohawk, iSlaveHunter, iMusketeer, iRedcoat, iCarolean, iFusilier, iRifleman, 
iMehalSefari, iGrenadier, iRocketeer, iGrenzer, iAlbionLegion, iChasseur, iAntiTank, iInfantry, iCommandoInfantry, iVietCong, iDigger, iSamInfantry, iGuulwadayaal, iMobileSam, iMarine, 
iNavySeal, iParatrooper, iMechanizedInfantry, iArcher, iJavelineer, iAsharittuBowman, iMedjay, iNativeArcher, iSkirmisher, iHolkan, iAtlatl, 
iKelebolo, iKshatriya, iLongbowman, iPatiyodha, iRattanArcher, iKalaka, iShortbowman, iDehqanArcher, iCrossbowman, iChokonu, iBalestriere, iChariot, iWarChariot, iHuluganni, 
iCidainh, iHorseman, iYanLifida, iAyrudzi, iCompanion, iNumidianCavalry, iAsvaka, iBerberFaris, iCamelRider, iCamelLancer, iHorseArcher, iAshina, iAspabarata, iHeavyHorseArcher, iMangudai, iKhampa, iOghuz, 
iCamelArcher, iGuy, iBedouinSheikh, iArmouredHorseman, iMalassay, iKhazarNobleLancer, iKontosCavalry, iSavaran, iFarari, iLancer, iMonaspa, iMamluk, iMobileGuard, iKeshik, iCataphract, iChambul, iChangSuek, iCrusader, iHospitaller, iPistolier, 
iHakkapeliitta, iMountedBrave, iCamelGunner, iZamburak, iCuirassier, iHajana, iGendarme, iConquistador, iWingedHussar, iSowar, iBannerman, iHussar, iCossack, 
iLlanero, iDragoon, iCassay, iIkhwan, iGrenadierCavalry, iCavalry, iBittereinder, iRural, iLightHorse, iWarElephant, iVaru, iBallistaElephant, iTank, iPanzer, 
iMainBattleTank, iGunship, iCatapult, iTrojanHorse, iSiegeRam, iBallista, iTrebuchet, iBombard, iHwacha, iLantaka, iSiegeElephant, 
iGreatBombard, iCannon, iGribeauval, iArtillery, iMachineGun, iHowitzer, iMobileArtillery, iWorkboat, iGalley, iFlotilla, iWaka, iFishingBoats,
iBireme, iWarGalley, iHeavyGalley, iDromon, iLongship, iPirogue, iCog, iBeden, iDharani, iDhow, iGalleass, iDjong, 
iKobukson, iLanternas, iCaravel, iCarrack, iGalleon, iFluyt, iPrivateer, iBaghlah, iCorsair, iFrigate, iShipOfTheLine, 
iManOfWar, iSteamship, iIronclad, iTorpedoBoat, iCruiser, iTransport, iDestroyer, iCorvette, iBattleship, iMissileCruiser, 
iStealthDestroyer, iSubmarine, iNuclearSubmarine, iCarrier, iSupercarrier, iBiplane, iFighter, iZero, iJetFighter, iBomber, 
iFlyingFortress, iStealthBomber, iGuidedMissile, iDrone, iNuclearBomber, iICBM, iSatellite, iGreatProphet, iGreatArtist, iGeorgianGreatArtist, iGreatScientist, 
iGreatMerchant, iGreatEngineer, iGreatStatesman, iGreatGeneral, iArgentineGreatGeneral, iGreatSpy, iGreatTrekker, iFemaleGreatProphet, iFemaleGreatArtist, iFemaleGreatScientist, iFemaleGreatMerchant, 
iFemaleGreatEngineer, iFemaleGreatStatesman, iFemaleGreatGeneral, iFemaleGreatSpy, iFemaleGreatTrekker, iSlave, iBenineseSlave, iJonow, iAztecSlave) = range(iNumUnits)

lGreatPeopleUnits = [iGreatProphet, iGreatArtist, iGreatScientist, iGreatMerchant, iGreatEngineer, iGreatStatesman, iGreatGeneral, iGreatSpy, iGreatTrekker]

dFemaleGreatPeople = {
iGreatProphet : iFemaleGreatProphet,
iGreatArtist : iFemaleGreatArtist,
iGreatScientist : iFemaleGreatScientist,
iGreatMerchant : iFemaleGreatMerchant,
iGreatEngineer : iFemaleGreatEngineer,
iGreatStatesman : iFemaleGreatStatesman,
iGreatGeneral : iFemaleGreatGeneral,
iGreatSpy : iFemaleGreatSpy,
iGreatTrekker : iFemaleGreatTrekker, # No female art yet
}


iNumUnitRoles = 23
(iBase, iDefend, iAttack, iCounter, iShock, iHarass, iCityAttack, iWorkerSea, iSettle, iSettleSea, 
iAttackSea, iAssaultSea, iFerry, iEscort, iExplore, iShockCity, iSiege, iCitySiege, iExploreSea, iSkirmish, 
iLightEscort, iWork, iMissionary) = range(iNumUnitRoles)

# Promotions
iMercenary = 81
iDesertAdaptation = 82
iSteppeAdaptation = 83
iVolunteer = 84


iNumBonuses = 55
(iAluminium, iAmber, iCamel, iCitrus, iCoal, iCopper, iDates, iHorse, iIron, iMarble,
iOil, iStone, iUranium, iBanana, iClam, iCorn, iCow, iCrab, iDeer, iFish,
iPig, iPotato, iRice, iSheep, iWheat, iCocoa, iCoffee, iCotton, iDye, iFur,
iGems, iGold, iIncense, iIvory, iJade, iMillet, iObsidian, iOlives, iFertilizer, iOpium, iPearls,
iRareEarths, iRubber, iSalt, iSilk, iSilver, iSpices, iSugar, iTea, iTobacco, iWine,
iWhales, iSoccer, iSongs, iMovies) = range(iNumBonuses)

iNumBonusVarieties = 19
(iDyeCochineal, iDyeMurex, iDyeHenna, iSpicesCinnamon, iSpicesNutmeg, iSpicesSaffron, iSpicesVanilla, iGemsTurquoise, iGemsDiamonds, iGemsRuby, iGemsSapphire, 
iGemsEmeralds, iSheepLlama, iSheepBlack, iCowBrown, iPigFurry, iIvoryAfrican, iCitrusOranges, iCrabShrimp) = range(iNumBonuses, iNumBonuses + iNumBonusVarieties)


iNumBuildings = 201
(iPalace, iBarracks, iSlaveBarracks, iAgogeBarracks, iKalliu, iSoldattorp, iIkhanda, iGranary, iMudbrickHouse, iPotteryHouse, iTannery, iPaganTemple, iWeaver, iCarpetWorkshop, iMbwadi, 
iMonument, iChokweSculpture, iKurgan, iOrkhonInscription, iRunestone, iTholos, iObelisk, iMenhir, iStele, iCandi, iEdict, iMalae, iMudbrickPyramid, iTotemPole, iWalls, iTowerHouse, iKotel,
iDun, iStable, iSilkTent, iOrtege, iLibrary, iSufiShrine, iStoneHermitage, iEdubba, iTaixue, iKyaung, iCalmecac, iHarbor, iAqueduct, iBakery,
iQanat, iBaray, iNoria, iStepwell, iTheatre, iJujuHall, iOdeon, iWaterPuppetTheatre, iHippodrome, iPavilion, iArena, 
iBallCourt, iCharreadaArena, iSambadrome, iGarden, iLighthouse, iSilkRoadTradePort, iCoastalOutpost, iHighlandOutpost, iGudang, iTradingPost, iVolok, iJeweller, iGumWorkshop, iGlassmaker, iObsidianWorkshop, iArcheryRange, iSchool, iArabicSchool, iFairground, iManor, iReliquary, iInn, iGuildHall, iJullaGuild, iRacingTrack, iLaagerCamp, iDrummingStation, iInfirmary,
iMarket, iSouk, iBazaar, iGrainMarket, iAgora, iForum, iCaravanserai, iWangara, iFloatingMarket, iJail, iDivan, iOstrog, iBath, iReservoir, 
iHammam, iForge, iAmuletWorkshop, iRoyalForge, iKiln, iBloomeryBuilding, iArtStudio, iCastle, iZimbabweBuilding, iRibat, iTsikhe, iKasbah, iCitadel, iIslandFort, iPharmacy, iAlchemist, 
iGrocer, iPostOffice, iTambo, iBasqaq, iWharf, iCoffeehouse, iCoffeePort, iSalon, iChocolaterie, iBank, iPiaohao, iTreasury, iCouncil, iRathaus, iSejmik, iConstabulary, iMountedPolice, iCustomsHouse, 
iFeitoria, iUniversity, iSeowon, iGompa, iCivicSquare, iGopuram, iSewer, iStarFort, iCastleMosque, 
iEstate, iMausoleum, iHacienda, iDrydock, iLevee, iEarthMoat, iPolder, iAgriculturalFactory, iObservatory, iWarehouse, iCourthouse, iChancery, iExchequer, 
iFactory, iAssemblyPlant, iZaibatsu, iDistillery, iPark, iBagh, iCoalPlant, iRailwayStation, iLaboratory, iCsiro, iAbattoir, 
iColdStoragePlant, iGrainSilo, iNewsPress, iGasPlant, iAmmoniaPlant, iIndustrialPark, iOilDepot, iCinema, iHospital, iSupermarket, iPublicTransportation, iDepartmentStore, iMall, 
iBroadcastTower, iIntelligenceAgency, iElectricalGrid, iWaterworks, iAirport, iBunker, iBombShelters, iHydroPlant, iSecurityBureau, iStadium, iRugbyStadium, iContainerTerminal, 
iNuclearPlant, iDiagnosticsCenter, iSupercomputer, iHotel, iRecyclingCenter, iLogisticsCenter, iSolarPlant, iFiberNetwork, iAutomatedFactory, iVerticalFarm) = range(iNumBuildings)

iNumReligiousBuildings = 44
iFirstReligiousBuilding = iNumBuildings
iNumBuildings += iNumReligiousBuildings
(iJewishTemple, iJewishCathedral, iJewishMonastery, iJewishShrine, iOrthodoxTemple, iOrthodoxCathedral, iOrthodoxMonastery, iOrthodoxShrine, iCatholicTemple, iCatholicCathedral, 
iCatholicMonastery, iCatholicShrine, iProtestantTemple, iProtestantCathedral, iProtestantMonastery, iProtestantShrine, iIslamicTemple, iIslamicCathedral, iIslamicMonastery, iIslamicShrine,  iHinduTemple, iHinduCathedral, iHinduMonastery, iHinduShrine, iBuddhistTemple, iBuddhistCathedral, iBuddhistMonastery, iBuddhistShrine, iConfucianTemple, iConfucianCathedral, iConfucianMonastery, iConfucianShrine, iTaoistTemple, iTaoistCathedral, iTaoistMonastery, iTaoistShrine, iZoroastrianTemple, iZoroastrianCathedral, iZoroastrianMonastery, iZoroastrianShrine, iShiaTemple, iShiaCathedral, iShiaMonastery, iShiaShrine,) = range(iFirstReligiousBuilding, iNumBuildings)

iNumNationalWonders = 22
iFirstNationalWonder = iNumBuildings
iNumBuildings += iNumNationalWonders
(iAcademy, iAdministrativeCenter, iManufactory, iArmoury, iMuseum, iGreatIcon, iStockExchange, iFrontier, iTradingCompanyBuilding, iIberianTradingCompanyBuilding, iNationalMonument, iNationalTheatre, 
iNationalGallery, iNationalCollege, iMilitaryAcademy, iSecretService, iCaravanSupply, iIronworks, iRedCross, iNationalPark, iCentralBank, iSpaceport) = range(iFirstNationalWonder, iNumBuildings)

iNumGreatWonders = 166 # different from DLL constant because that includes national wonders
iFirstWonder = iNumBuildings
iNumBuildings += iNumGreatWonders
(iGreatSphinx, iTempleOfAmun, iNuri, iEtemenaki, iAbuSimbel, iGreatBath, iTrajansColumn, iCircusMaximus, iPyramids, iOracle, iGreatWall, iIshtarGate, iTerracottaArmy, iHangingGardens, iKnossosPalace, iGreatCothon, iDujiangyan, iApadanaPalace, iGreatEnclosure, iHararGates, iRoyalKraal, iStonetownFort, iKulumbimbi, iKasubiTombs, iRoyalRova,
iColossus, iGreatMausoleum, iAquaAppia, iParthenon, iPyramidOfTheSun, iStatueOfZeus, iTempleOfArtemis, iGreatLighthouse, iMoaiStatues, iFlavianAmphitheatre, 
iPantheon, iAlKhazneh, iOuadaneKsar, iTempleOfKukulkan, iMachuPicchu, iGreatLibrary, iFloatingGardens, iGondeshapur, iJetavanaramaya, iNalanda, iTheodosianWalls, iHagiaSophia, 
iBorobudur, iMezquita, iShwedagonPaya, iMountAthos, iIronPillar, iPrambanan, iSalsalBuddha, iCheomseongdae, iTombOfAskia, iHimejiCastle, iGrandCanal, 
iWatPreahPisnulok, iKhajuraho, iGreatAdobeMosque, iSpiralMinaret, iOsunOsogbo, iProphetsMosque, iAlhambra, iAlAzhar, iDomeOfTheRock, iHouseOfWisdom, iIyanuwo, iKrakDesChevaliers, iMonolithicChurch, iUniversityOfSankore, iAitBenhaddou, iNotreDame, iNarekavank,
iOldSynagogue, iSaintSophia, iItchanKhala, iSilverTreeFountain, iRoseGardenPalace, iSantaMariaDelFiore, iAlamut, iSanMarcoBasilica, iSistineChapel, iPorcelainTower, iTopkapiPalace, iKremlin, 
iSaintThomasChurch, iVijayaStambha, iGurEAmir, iRedFort, iTajMahal, iForbiddenPalace, iVersailles, iBlueMosque, iEscorial, iTorreDeBelem, 
iPotalaPalace, iOxfordUniversity, iHarmandirSahib, iSaintBasilsCathedral, iBourse, iItsukushimaShrine, iImageOfTheWorldSquare, iLouvre, iEmeraldBuddha, iShalimarGardens, 
iTrafalgarSquare, iHermitage, iGuadalupeBasilica, iSaltCathedral, iAmberRoom, iStatueOfLiberty, iBrandenburgGate, iAbbeyMills, iBellRockLighthouse, iChapultepecCastle, 
iEiffelTower, iWestminsterPalace, iTriumphalArch, iMenloPark, iCrystalPalace, iTsukijiFishMarket, iBrooklynBridge, iHollywood, iEmpireStateBuilding, iLasLajasSanctuary, 
iPalaceOfNations, iMoleAntonelliana, iNeuschwanstein, iFrontenac, iWembley, iLubyanka, iCristoRedentor, iMetropolitain, iNobelPrize, iGoldenGateBridge, 
iBletchleyPark, iSagradaFamilia, iTiananmenSquare, iCERN, iItaipuDam, iGraceland, iCNTower, iPentagon, iUnitedNations, iCrystalCathedral, iMotherlandCalls, 
iBerlaymont, iWorldTradeCenter, iAtomium, iIronDome, iHarbourOpera, iLotusTemple, iFloralisGenerica, iGlobalSeedVault, iGardensByTheBay, iBurjKhalifa, iHubbleSpaceTelescope, 
iChannelTunnel, iSkytree, iOrientalPearlTower, iDeltaWorks, iSpaceElevator, iLargeHadronCollider, iITER) = range(iFirstWonder, iNumBuildings)

iTemple = iJewishTemple #generic
iCathedral = iJewishCathedral #generic
iMonastery = iJewishMonastery #generic
iShrine = iJewishShrine #generic

iPlague = iNumBuildings
iNumBuildingsPlague = iNumBuildings+1

#Civics
iNumCivics = 42
(iChiefdom, iDespotism, iMonarchy, iRepublic, iElective, iStateParty, iDemocracy,
iPersonalism, iCitizenship, iVassalage, iTheocracy, iBureaucracy, iStratocracy, iConstitution,
iTraditionalism, iSlavery, iManorialism, iCasteSystem, iIndividualism, iTotalitarianism, iEgalitarianism,
iReciprocity, iRedistribution, iMerchantTrade, iRegulatedTrade, iFreeEnterprise, iCentralPlanning, iPublicWelfare,
iAnimism, iDeification, iClergy, iSyncretism, iMonasticism, iFanaticism, iSecularism,
iKinship, iThalassocracy, iHegemony, iIsolationism, iColonialism, iNationhood, iMultilateralism) = range(iNumCivics)

iNumCivicCategories = 6
(iCivicsGovernment, iCivicsLegitimacy, iCivicsSociety, iCivicsEconomy, iCivicsReligion, iCivicsTerritory) = range(iNumCivicCategories)

#Specialists
iNumSpecialists = 21
(iSpecialistCitizen, iSpecialistPriest, iSpecialistArtist, iSpecialistScientist, iSpecialistMerchant, iSpecialistEngineer, iSpecialistStatesman,
iSpecialistGreatProphet, iSpecialistGreatArtist, iSpecialistGreatScientist, iSpecialistGreatMerchant, iSpecialistGreatEngineer, iSpecialistGreatStatesman, iSpecialistGreatGeneral, iSpecialistGreatSpy, 
iSpecialistResearchSatellite, iSpecialistCommercialSatellite, iSpecialistMilitarySatellite, iSpecialistTrekker, iSpecialistGreatTrekker, 
iSpecialistSlave) = range(iNumSpecialists)

lGreatSpecialists = [iSpecialistGreatProphet, iSpecialistGreatArtist, iSpecialistGreatScientist, iSpecialistGreatMerchant, iSpecialistGreatEngineer, iSpecialistGreatStatesman, iSpecialistGreatGeneral, iSpecialistGreatSpy]

#Stability Levels
iNumStabilityLevels = 5
(iStabilityCollapsing, iStabilityUnstable, iStabilityShaky, iStabilityStable, iStabilitySolid) = range(iNumStabilityLevels)
StabilityLevelTexts = ["TXT_KEY_STABILITY_COLLAPSING", "TXT_KEY_STABILITY_UNSTABLE", "TXT_KEY_STABILITY_SHAKY", "TXT_KEY_STABILITY_STABLE", "TXT_KEY_STABILITY_SOLID"]

#Stability Types
iNumStabilityTypes = 5
(iStabilityExpansion, iStabilityEconomy, iStabilityDomestic, iStabilityForeign, iStabilityMilitary) = range(iNumStabilityTypes)
StabilityTypesTexts = ["TXT_KEY_STABILITY_CATEGORY_EXPANSION", "TXT_KEY_STABILITY_CATEGORY_ECONOMY", "TXT_KEY_STABILITY_CATEGORY_DOMESTIC", "TXT_KEY_STABILITY_CATEGORY_FOREIGN", "TXT_KEY_STABILITY_CATEGORY_MILITARY"]

#Stability Parameters
iNumStabilityParameters = 24 # Aeons - Added Decadence
(iParameterCorePeriphery, iParameterAdministration, iParameterSeparatism, iParameterRecentExpansion, iParameterRazedCities, iParameterIsolationism,	# Expansion
iParameterEconomicGrowth, iParameterTrade, iParameterMercantilism, iParameterCentralPlanning,								# Economy
iParameterHappiness, iParameterDecadence, iParameterCivicCombinations, iParameterCivicsEraTech, iParameterReligion,								# Domestic
iParameterVassals, iParameterDefensivePacts, iParameterRelations, iParameterNationhood, iParameterFanaticism, iParameterMultilateralism,			# Foreign
iParameterWarSuccess, iParameterWarWeariness, iParameterBarbarianLosses) = range(iNumStabilityParameters)						# Military

#Regions
iNumRegions = 85
(rBritain, rIreland, rFrance, rIberia, rItaly, rLowerGermany, rCentralEurope, rBalkans, rGreece, rPoland,
rBaltics, rScandinavia, rRuthenia, rPonticSteppe, rEuropeanArctic, rUrals, rAnatolia, rCaucasus, rLevant, rMesopotamia,
rArabia, rEgypt, rNubia, rMaghreb, rPersia, rKhorasan, rTransoxiana, rSindh, rPunjab, rRajputana,
rHindustan, rBengal, rDeccan, rDravida, rIndochina, rIndonesia, rPhilippines, rSouthChina, rNorthChina, rKorea,
rJapan, rTibet, rTarimBasin, rMongolia, rManchuria, rAmur, rCentralAsianSteppe, rSiberia, rAustralia, rOceania,
rEthiopia, rHornOfAfrica, rSwahiliCoast, rGreatLakes, rZambezi, rMadagascar, rCape, rKalahari, rCongo, rGuinea, 
rSahel, rSahara, rAtlanticSeaboard, rDeepSouth, rMidwest, rGreatPlains, rAridoamerica, rCalifornia, rCascadia, rOntario, 
rQuebec, rMaritimes, rAmericanArctic, rCaribbean, rMesoamerica, rCentralAmerica, rNewGranada, rAndes, rAmazonia, rBrazil, 
rSouthernCone, rAntarctica, rHinduKush, rRussia, rVolga) = range(iNumRegions)

iNumWaterRegions = 87
(rMediterraneanSea, rBlackSea, rCaspianSea, rBalticSea, rNorthSea, rAtlanticOcean, rCaribbeanSea, rGulfOfMexico, rHudsonBay, rArcticOcean,
rRedSea, rArabianSea, rPersianGulf, rBayOfBengal, rIndianOcean, rAustralasianSea, rSouthChinaSea, rEastChinaSea, rSeaOfJapan, rSeaOfOkhotsk, 
rBeringSea, rPacificOcean, rSouthernOcean, rVanern, rVattern, rInari, rPaijanne, rOulu, rSaimaa, rPeipus, 
rLadoga, rOnega, rVan, rSevan, rUrmia, rAralSea, rTengiz, rBalkhash, rIssykKul, rAlakol, 
rZaysan, rUvs, rKhovsgol, rBaikal, rTaymyr, rHulun, rQinghai, rLopNur, rSiling, rDongting, 
rPoyang, rTai, rTonleSap, rSetoInlandSea, rEyre, rChad, rTana, rTurkana, rNyanza, rMwitanzege, 
rRweru, rTanganyika, rMweru, rBangweulu, rRukwa, rMalawi, rGreatBear, rTidee, rAthabasca, rReindeer, 
rDubawt, rBaker, rWinnipeg, rSuperior, rMichigan, rHuron, rErie, rLakeOntario, rMistassini, rLobstick, 
rGreatSalt, rNicaragua, rTiticaca, rMarChiquita, rKhanka, rZambuye, rMaiNdombe) = range(100, 100 + iNumWaterRegions)

lEuropeProper = [rBritain, rIreland, rFrance, rIberia, rItaly, rLowerGermany, rCentralEurope, rBalkans, rGreece, rPoland, rBaltics, rScandinavia, rRuthenia, rPonticSteppe]
lEuropeAsia = [rEuropeanArctic, rUrals, rSiberia]
lMiddleEast = [rAnatolia, rCaucasus, rLevant, rMesopotamia, rArabia, rPersia, rKhorasan, rTransoxiana]
lIndia = [rSindh, rPunjab, rRajputana, rHindustan, rBengal, rDeccan, rDravida]
lEastAsia = [rSouthChina, rNorthChina, rKorea, rJapan, rTibet, rTarimBasin, rMongolia, rManchuria, rAmur, rCentralAsianSteppe]
lSouthEastAsia = [rIndochina, rIndonesia, rPhilippines]
lNorthAfrica = [rEgypt, rNubia, rMaghreb]
lSubSaharanAfrica = [rEthiopia, rHornOfAfrica, rSwahiliCoast, rGreatLakes, rZambezi, rMadagascar, rCape, rKalahari, rCongo, rGuinea, rSahel, rSahara]
lSouthAmerica = [rNewGranada, rAndes, rAmazonia, rBrazil, rSouthernCone]
lCentralAmerica = [rCaribbean, rMesoamerica, rCentralAmerica]
lNorthAmerica = [rAtlanticSeaboard, rDeepSouth, rMidwest, rGreatPlains, rAridoamerica, rCalifornia, rCascadia, rOntario, rQuebec, rMaritimes, rAmericanArctic]
lOceania = [rAustralia, rOceania]
# Aeons
lMediterraneanRegions = [rIberia + rItaly + rFrance + rGreece + rAnatolia + rEgypt + rMaghreb + rLevant]

lEurope = lEuropeProper + lEuropeAsia
lAfrica = lNorthAfrica + lSubSaharanAfrica
lSouthAsia = lIndia + lSouthEastAsia
lAsia = lMiddleEast + lSouthAsia + lEastAsia
lAmerica = lSouthAmerica + lCentralAmerica + lNorthAmerica


lNewWorld = lAmerica + lOceania

lLateColonialRegions = lAfrica + lSouthAsia + lEastAsia + [rLevant, rMesopotamia, rArabia, rPersia, rKhorasan, rTransoxiana]

dCivGroupRegions = {
	iCivGroupEurope: lEurope,
	iCivGroupEastAsia: lEastAsia,
	iCivGroupSouthAsia: lSouthAsia,
	iCivGroupMiddleEast: lMiddleEast,
	iCivGroupAfrica: lAfrica,
	iCivGroupAmerica: lAmerica,
	iCivGroupNorthAfrica: lNorthAfrica,
	iCivGroupOceania: lOceania,
	iCivGroupMediterranean: lMediterraneanRegions,
}

#Projects

iNumProjects = 23
(iSuezCanal, iPanamaCanal, iManhattanProject, iTheInternet, iHumanGenome, iSDI, iGPS, iISS, iBallisticMissile, iFirstSatellite, iManInSpace, iLunarLanding,
iGoldenRecord, iMarsMission, iLunarColony, iInterstellarProbe, iMarsFraming, iMarsPowerSource, iMarsExtractor, iMarsHabitat, iMarsHydroponics, iMarsLaboratory, iMarsControlCenter) = range(iNumProjects)

lMarsBaseComponents = [iMarsFraming, iMarsPowerSource, iMarsExtractor, iMarsHabitat, iMarsHydroponics, iMarsLaboratory, iMarsControlCenter]

#Eras

iNumEras = 7
(iAncient, iClassical, iMedieval, iRenaissance, iIndustrial, iGlobal, iDigital) = range (iNumEras)

# Culture

iNumCultureLevels = 7
(iCultureLevelNone, iCultureLevelPoor, iCultureLevelFledgling, iCultureLevelDeveloping, iCultureLevelRefined, iCultureLevelInfluential, iCultureLevelLegendary) = range(iNumCultureLevels)


#Improvements

iNumImprovements = 33
(iLandWorked, iWaterWorked, iCityRuins, iHut, iFarm, iPaddyField, iFishingBoats, iHarvestBoats, iOceanFishery, iWhalingBoats, 
iMine, iSlaveMine, iWorkshop, iLumbermill, iWindmill, iWatermill, iPlantation, iSlavePlantation, iQuarry, iPasture, 
iCamp, iWell, iOffshorePlatform, iOrchard, iCottage, iHamlet, iVillage, iTown, iFort, iForestPreserve, 
iMarinePreserve, iSolarCollector, iCanal) = range(iNumImprovements)

iNumRoutes = 4
(iRouteRoad, iRouteRailroad, iRouteRomanRoad, iRouteHighway) = range(iNumRoutes)

#feature & terrain

iNumFeatures = 14
(iSeaIce, iJungle, iOasis, iFloodPlains, iForest, iMud, iCape, iIslands, iRainforest, iFallout, 
iTaiga, iSavanna, iStrait, iIslandsStrait) = range(iNumFeatures)

iNumTerrains = 19
(iGrass, iPlains, iDesert, iTundra, iSnow, iCoast, iOcean, iTerrainPeak, iTerrainHill, iMarsh, 
iLagoon, iArcticCoast, iSemidesert, iSteppe, iMoorland, iSaltFlat, iSaltLake, iAtoll, iTerrainSavanna) = range(iNumTerrains)

#Plague
iImmunity = 20

# Victory
iVictoryPaganism = 10
iVictorySecularism = 11


#leaders
iNumLeaders = 227
(iLeaderBarbarian, iNativeLeader, iIndependentLeader, iDjoser, iHatshepsut, iRamesses, iPtolemy, iSargon, iWentAntu,
iMinos, iKindattu, iAshurbanipal, iWu, iTaizong, iHongwu, iMao, iHammurabi, iNebuchadnezzar, iMursili, iAgamemnon, iPericles, iAlexanderTheGreat, iSeleucus, iGeorge, iAsoka, 
iChandragupta, iShivaji, iGandhi, iHiram, iHannibal, iDavid, iTaharqa, iAmanirena, iMerkurios, iAlBashir, iAhoeitu, iTomyris, iCyrus, iDarius, iAlSaffar, iMithridates, iKhosrow, iLeonidas, 
iBrennus, iBoudica, iBrianBoru, iScipio, iJuliusCaesar, iAugustus, iMarcusAurelius, iPacal, iMasinissa, iYaghmurasen, iBoumediene, iTigranes, iAshot, iAndranik, iJuliusCivilis, iRajendra, iKrishnaDevaRaya, iEzana, iZaraYaqob, iMenelik, iSelassie, iGaiseric, iTopiltzin, 
iKanishka, iWangKon, iSejong, iNeangNeak, iSuryavarman, iAlaric, iDinghaCisse, iMansaMusa, iTraore, iConstantine, iJustinian, iBasil, iAttila, iCharlemagne, iPhilipAugustus, iLouis, iNapoleon, 
iDeGaulle, iSriJayanasa, iTunPerak, iKammu, iOdaNobunaga, iMeiji, iCanute, iHaakon, iChristian, iGerhardsen, iBumin, 
iAlpArslan, iShaybaniKhan, iTamerlane, iHarun, iQatadaIbnIdris, iSongtsen, iLobsangGyatso, iBulan, iDunamaDabbalemi, iRahman, iYaqub, iAhmad, iMohammedV, iHayamWuruk, iSuharto, 
iIsabella, iPhilip, iFranco, iTamar, iAlfred, iElizabeth, iVictoria, iChurchill, iArwaAlSulayhi, iAlQasim, iAlSallal, iBarbarossa, iCharles, iFrancis, 
iAnawrahta, iBayinnaung, iAmina, iUsumanDanFodio, iObasanjo, iYaroslav, iKhmelnytsky, iIsmaelSamani, iEwuare, iAlMuiz, iSaladin, iBaibars, iMuhammadAli, iNasser, iAdudAlDawla, iLeLoi, iHoChiMinh, iFakrAdDin, iAbdillaiDeria, iDawud, iNyerere, iKakamaTwale, iMutesa, iIdiAmin, iCasimir, iSobieski, iPilsudski, iWalesa, iBaldwin, iAfonso, 
iJoao, iMaria, iHuaynaCapac, iCastilla, iAbiBinOmar, iBarghash, iLorenzo, iCavour, iMussolini, iGenghisKhan, iKublaiKhan, iMontezuma, 
iSabuktigin, iTughluq, iAkbar, iBhutto, iMatope, iChangamire, iIanSmith, iAbuAmrUthman, iBourguiba, iUzbeg, iNaresuan, iMongkut, iGustav, iErlander, iIvan, iPeter, iCatherine, iAlexanderI, 
iStalin, iAhmadIbnIbrahim, iMehmed, iSuleiman, iMahmudII, iAtaturk, iMbemba, iMobutu, iSunniAli, iAmaraDunqas, iAbbas, iKhomeini, iAndrianampoinimerina, iTsiranana, iWillemVanOranje, iWilliam, iChibindaIlunga, iKangxi, iOsei, iYaaAsantewa, iFrederick, 
iBismarck, iHitler, iIbnSaud, iWashington, iLincoln, iRoosevelt, iPaulKruger, iSanMartin, iPeron, iJuarez, iSantaAnna, iCardenas, 
iBolivar, iShaka, iPedro, iVargas, iLeopold, iCurtin, iMacDonald, iTrudeau, iBotha, iNelsonMandela, iSittingBull) = range(iNumLeaders)

dResurrectionLeaders = CivDict({
	iChina : iHongwu,
	iIndia : iShivaji,
	iEgypt : iBaibars,
})

# update DLL constants when this changes
iNumPeriods = 56
(iPeriodPtolemaicEgypt, iPeriodMakuria, iPeriodSudan, iPeriodMing, iPeriodMaratha, 
iPeriodCarthage, iPeriodPonticScythia, iPeriodUnitedGreece, iPeriodModernGreece, iPeriodInsularCelts, iPeriodSeleucids, iPeriodAlgeria,
iPeriodAngloSaxons, iPeriodVijayanagara, iPeriodVandalAfrica, iPeriodVisigoths, iPeriodOstrogoths, 
iPeriodByzantineConstantinople, iPeriodByzantiumRoman, iPeriodNationalFrance, iPeriodMeiji, iPeriodDenmark, 
iPeriodNorway, iPeriodHejaz, iPeriodArabiaMesopotamia, iPeriodCastile, 
iPeriodModernSpain, iPeriodAustria, iPeriodSokoto, iPeriodNigeria, iPeriodUkraine, 
iPeriodModernBenin, iPeriodMisrEgypt, iPeriodBuyidBaghdad, iPeriodDelhi, iPeriodUnitedKingdom, 
iPeriodGreatBritain, iPeriodTanzania, iPeriodBuganda, iPeriodUganda, iPeriodUzbeks, 
iPeriodYuan, iPeriodMutapa, iPeriodRozwi, iPeriodRhodesia, iPeriodPeru, 
iPeriodZanzibar, iPeriodLateInca, iPeriodModernItaly, iPeriodOttomanConstantinople, iPeriodMughals, 
iPeriodPakistan, iPeriodSouthSudan, iPeriodQing, iPeriodModernGermany, iPeriodSouthAfricaUnion, ) = range(iNumPeriods)


dCivPeriods = {
	iEgypt: (iPeriodPtolemaicEgypt,),
	iNubia : (iPeriodMakuria, iPeriodSouthSudan),
	iChina : (iPeriodMing,),
	iIndia : (iPeriodMaratha,),
	iGreece : (iPeriodModernGreece, iPeriodUnitedGreece),
	iPhoenicia : (iPeriodCarthage,),
	iCelts : (iPeriodInsularCelts,),
	iDravidia : (iPeriodVijayanagara,),
	iByzantium : (iPeriodByzantineConstantinople, iPeriodByzantiumRoman),
	iFrance : (iPeriodNationalFrance,),
	iJapan : (iPeriodMeiji,),
	iNorse : (iPeriodDenmark, iPeriodNorway),
	iTurks : (iPeriodUzbeks),
	iSpain : (iPeriodCastile, iPeriodModernSpain),
	iHolyRome : (iPeriodAustria,),
	iEngland : (iPeriodUnitedKingdom, iPeriodGreatBritain),
	iMongols : (iPeriodYuan,),
	iInca : (iPeriodPeru, iPeriodLateInca),
	iItaly : (iPeriodModernItaly,),
	iTimurids : (iPeriodMughals, iPeriodPakistan,),
	iOttomans : (iPeriodOttomanConstantinople,),
	iManchuria : (iPeriodQing,),
	iGermany : (iPeriodModernGermany,),

	# Aeons
	iSparta: (iPeriodUnitedGreece),
	iScythia: (iPeriodPonticScythia),
	iMacedon : (iPeriodSeleucids),
	iNumidia: (iPeriodAlgeria),
	iGermania: (iPeriodAngloSaxons),
	iVandals: (iPeriodVandalAfrica),
	iGoths: (iPeriodOstrogoths, iPeriodVisigoths),
	iArabia: (iPeriodHejaz, iPeriodArabiaMesopotamia),
	iHausa: (iPeriodNigeria, iPeriodSokoto),
	iRus: (iPeriodUkraine),
	iBenin: (iPeriodModernBenin),
	iMisr: (iPeriodMisrEgypt),
	iBuyids: (iPeriodBuyidBaghdad),
	iGhorids: (iPeriodDelhi),
	iSwahili: (iPeriodTanzania),
	iBuganda: (iPeriodBuganda, iPeriodUganda),
	iZimbabwe: (iPeriodMutapa, iPeriodRozwi, iPeriodRhodesia),
	iOman: (iPeriodZanzibar),
	iZulu: (iPeriodSouthAfricaUnion),
	iBoers: (iPeriodSouthAfricaUnion),
	iSouthAfrica: (iPeriodSouthAfricaUnion),

	iFunj: (iPeriodSudan),
}

iNumImpacts = 6
(iImpactSuperMarginal, iImpactMarginal, iImpactLimited, iImpactSignificant, iImpactCritical, iImpactPlayer) = range(iNumImpacts)

lTradingCompanyCivs = [iSpain, iFrance, iEngland, iPortugal, iNetherlands, iOman]
lLateColonyCivs = lTradingCompanyCivs + [iGermany]

# Aeons - Remove these and just let anyone in the area get conqueror'd
#lMongolCivs = [iPersia, iByzantium, iTurks, iGokturks, iArabia, iRus, iParthia, iArmenia, iBuyids, iSamanids, iChina, iJerusalem, iGeorgia, iGhorids, iKhazars, iIndependent, iIndependent2]
#lArabiaCivs = [iPersia, iArmenia, iParthia, iGoths, iVandals, iEgypt, iByzantium, iRome, iCarthage]
#lFatimidCivs = [iArabia, iByzantium, iRome, iParthia, iPersia, iIndependent, iIndependent2]

iNumScenarios = 6
(i3000BC, i600AD, i1100AD, i1500AD, i1700AD, i1815AD) = range(6)
lScenarioStartYears = [-3000, 600, 1100, 1500, 1700, 1815]

# Stability overlay and editor
iNumPlotStabilityTypes = 4
(iCoreArea, iHistoricalArea, iConquestArea, iForeignArea) = range(iNumPlotStabilityTypes)
lStabilityColors = ["COLOR_CYAN", "COLOR_GREEN", "COLOR_YELLOW", "COLOR_RED"]
lPresetValues = [3, 20, 90, 200, 500, 700]

iMaxWarValue = 12
lWarMapColors = ["COLOR_RED", "COLOR_PLAYER_ORANGE", "COLOR_YELLOW", "COLOR_GREEN", "COLOR_PLAYER_DARK_GREEN", "COLOR_BLUE"]

lReligionMapColors = ["COLOR_PLAYER_ORANGE", "COLOR_YELLOW", "COLOR_GREEN", "COLOR_CYAN"]
lReligionMapTexts = ["TXT_KEY_CULTURELEVEL_NONE", "TXT_KEY_WB_RELIGIONMAP_MINORITY", "TXT_KEY_WB_RELIGIONMAP_PERIPHERY", "TXT_KEY_WB_RELIGIONMAP_HISTORICAL", "TXT_KEY_WB_RELIGIONMAP_CORE"]

lNetworkEvents = {
	"CHANGE_COMMERCE_PERCENT" :	1200,
}

newline = "[NEWLINE]"
bullet = "[ICON_BULLET]"
event_bullet = "INTERFACE_EVENT_BULLET"
event_cancel = "INTERFACE_BUTTONS_CANCEL"